/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * About_Us.java
 *
 * Created on Oct 10, 2017, 7:46:58 PM
 */

/**
 *
 * @author Yuvansh
 */
public class About_Us extends javax.swing.JFrame {

    /** Creates new form About_Us */
    public About_Us() {
        initComponents();
      jTextArea1.setCaretPosition(0);
      jTextArea2.setCaretPosition(0);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        setMinimumSize(new java.awt.Dimension(866, 518));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Algerian", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ABOUT US");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(320, 10, 210, 48);

        jTextArea1.setBackground(new java.awt.Color(255, 255, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("High Tower Text", 3, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(204, 0, 102));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("     !!   GARNISH RESTAURANT   !!\n\nGarnish is a casual fine dining restaurant, offering eclectic Indian cuisine and warm hospitality. Our food is sourced from top quality seasonal ingredients featuring a high percentage of organic products. Our menu offers diversified and healthy options to choose from. \n\nWe consider Garnish to be a truly “Indian” restaurant, honouring many different cooking traditions and interpreting them with our unique creative vision.\n\nOur approach towards the operation of the restaurant is truly cooperative. We believe that every single member of our staff is an integral part to our success. We are defined as a main stream casual dining restaurant that caters to the community and local businesses. \n\nWe believe in providing friendly, attentive service in a warm environment by staff and owners that truly enjoy their job.\n\nOur passionate desire to provide extraordinary value for our guests in afriendly environment, along with a sincere commitment to support the communities in which we do business, goes to the heart of what differentiates Garnish from other restaurants.\n\n It is because of you, our guests that we have been able to realize a dream and create the company and culture that thrives today...\n\n  !!!\n         Thank you for being the biggest\n                          and\n           most important part of what\n                         keeps \n                  our dreams alive\n                                                           !!!\n");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(460, 70, 370, 400);

        jLabel5.setBackground(new java.awt.Color(204, 204, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/471074.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 10, 200, 92);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon.png"))); // NOI18N
        jButton6.setToolTipText("<html><font color=\"RED\" face=\"JOKERMAN\">HOME</font></html>");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(220, 10, 50, 50);

        jTextArea2.setBackground(new java.awt.Color(255, 255, 204));
        jTextArea2.setColumns(20);
        jTextArea2.setEditable(false);
        jTextArea2.setFont(new java.awt.Font("High Tower Text", 3, 18)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(204, 0, 102));
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText(" The Mission of GARNISH RESTAURANT,\n Our continuing purpose is to .....\n                                  \n1.Satisfy customer needs in the best way                possible.\n\n2.Ensure a profit for continued success and            enhancement of an expanding customer base.\n\n3.Be an asset to this business and to the                  community where we work and live.\n\n4.Provide a friendly atmosphere of genuine            hospitality to our customers and fellow                employees.\n\n5.Serve quality food and beverage at a                  reasonable price.");
        jTextArea2.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(40, 280, 390, 190);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main-dining-room.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 100, 390, 170);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 850, 480);

        setSize(new java.awt.Dimension(869, 521));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Welcome_Screen_ ws=new Welcome_Screen_();
        ws.setVisible(true);
        this.setVisible(false);
}//GEN-LAST:event_jButton6ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new About_Us().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables

}
