import java.awt.Color;
import java.awt.Font;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Billing_Form.java
 *
 * Created on Nov 7, 2017, 9:16:51 PM
 */

/**
 *
 * @author Yuvansh
 */
public class Billing_Form extends javax.swing.JFrame {
    Connection con = null;
Statement stmt = null;
ResultSet rs=null;
String on,ph,so,fnm,t,c ,m;
int p,nop;
Date d;
int ta=0;
 int a = 0;

    /** Creates new form Billing_Form */
    public Billing_Form() {
        initComponents();
               try{
            Class.forName("com.mysql.jdbc.Driver");
          con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","");
        stmt= con.createStatement();
        int ros = stmt.executeUpdate("delete from bill where foodname ='null';");
        }
             catch(Exception e)
                 {
            JOptionPane.showMessageDialog(null,e);
        }
         try{
            Class.forName("com.mysql.jdbc.Driver");
          con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","");
        stmt= con.createStatement();
         ResultSet ros = stmt.executeQuery("select fname, lname from username u ,signup s where u.uname=s.username;");
         Font font =new Font("CHILLER",Font.BOLD,30);
          while(ros.next()){
        String f = ros.getString("fname");
        String l = ros.getString("lname");
        String cm=f+"  "+l;
        um.setFont(font);
        um.setText(""+cm);
        }
         }
        catch(Exception e)
                 {
            JOptionPane.showMessageDialog(null,e);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        in = new javax.swing.JTextField();
        Remove = new javax.swing.JButton();
        GenerateBill = new javax.swing.JButton();
        Buy = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        phno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tax = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        um = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1315, 800));
        getContentPane().setLayout(null);

        jTable1.setBackground(new java.awt.Color(204, 255, 204));
        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ORDER NO.", "CUST NAME", "PHONE NO", "FOODNAME", "ITEMCODE", "TYPE", "PRICE", "DATE", "NO OF PERSON", "MODE OF PAYMENT"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setOpaque(false);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 190, 1070, 440);

        jLabel8.setBackground(new java.awt.Color(204, 204, 255));
        jLabel8.setForeground(new java.awt.Color(255, 255, 204));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/471074.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 20, 200, 90);

        jLabel2.setFont(new java.awt.Font("Raavi", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Total Amount To Be Paid:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 150, 200, 20);

        jLabel3.setFont(new java.awt.Font("Raavi", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Rs.");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(250, 150, 30, 20);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(500, 110, 70, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Remove Any Item :- ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(730, 80, 140, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("Item Name :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(740, 150, 70, 15);
        getContentPane().add(in);
        in.setBounds(830, 150, 180, 20);

        Remove.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Remove.setText("Remove");
        Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveActionPerformed(evt);
            }
        });
        getContentPane().add(Remove);
        Remove.setBounds(910, 120, 100, 27);

        GenerateBill.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        GenerateBill.setText("Generate Bill");
        GenerateBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateBillActionPerformed(evt);
            }
        });
        getContentPane().add(GenerateBill);
        GenerateBill.setBounds(480, 150, 110, 27);

        Buy.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Buy.setText("Buy");
        Buy.setEnabled(false);
        Buy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyActionPerformed(evt);
            }
        });
        getContentPane().add(Buy);
        Buy.setBounds(610, 150, 100, 27);

        Cancel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Cancel.setText("CLOSE");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        getContentPane().add(Cancel);
        Cancel.setBounds(870, 20, 110, 27);
        getContentPane().add(phno);
        phno.setBounds(200, 110, 180, 20);

        jLabel6.setForeground(new java.awt.Color(255, 255, 51));
        jLabel6.setText("TAX:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(590, 110, 50, 20);
        getContentPane().add(tax);
        tax.setBounds(640, 110, 70, 20);
        getContentPane().add(total);
        total.setBounds(280, 150, 170, 28);

        jLabel7.setForeground(new java.awt.Color(255, 255, 51));
        jLabel7.setText("TOTAL AMOUNT");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(390, 110, 110, 20);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon.png"))); // NOI18N
        jButton6.setToolTipText("<html><font color=\"RED\" face=\"JOKERMAN\">HOME</font></html>");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(180, 20, 50, 50);

        um.setFont(new java.awt.Font("Bell MT", 3, 18)); // NOI18N
        um.setForeground(new java.awt.Color(255, 255, 51));
        getContentPane().add(um);
        um.setBounds(440, 60, 220, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 0));
        jLabel9.setText("Item Code :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(740, 120, 70, 15);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(830, 120, 70, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 0));
        jLabel10.setText("ENTER PHONE NMBER");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 110, 160, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 204, 204));
        jLabel11.setText("CUSTOMER NAME :-");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(300, 60, 130, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grey-elegance-HD.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1140, 720);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveActionPerformed
        // TODO add your handling code here:
         DefaultTableModel tm = (DefaultTableModel)jTable1.getModel();

        tm.setRowCount(0);
         a = Integer.parseInt(jTextField3.getText());
             try{
           Class.forName("com.mysql.jdbc.Driver");
        Connection    ctton= DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
            Statement stttmt = ctton.createStatement();
        int rls = stttmt.executeUpdate("delete from billing where phn_number='"+phno.getText()+"' and item='"+in.getText()+"';");

        } catch(Exception e)
       {
            JOptionPane.showMessageDialog(null, e);
        }

                            /**/
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection cone= DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
            Statement stmte = cone.createStatement();
            int dpt = stmte.executeUpdate("delete from bill where sno='"+a+"';");
        } catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
                              /**/
     
          try{
            Class.forName("com.mysql.jdbc.Driver");
           Connection conq= DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
           Statement stmtq = conq.createStatement();
            ResultSet rsq = stmtq.executeQuery("select * from bill b,orders o where o.Phone_Number='"+phno.getText()+"';");
          Date dt;
         int pri,nopp;
         String onn,phn,sno,fdm,ty,cn ,mp;
            while(rsq.next()){
                sno = rsq.getString("sno");
                pri = rsq.getInt("price");
                fdm = rsq.getString("foodname");
                ty = rsq.getString("type");
                nopp=rsq.getInt("no_of_person");
                phn=rsq.getString("phone_number");
                cn=rsq.getString("cust_name");
                mp=rsq.getString("mode_of_payment");
                dt=rsq.getDate("date");
                onn=rsq.getString("odr_number");
                Object row[] = {onn,cn,phn,fdm,sno,ty,pri,dt,nopp,mp};
               tm.addRow(row);}
          }
        
          
          catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }

                                               /* */

         try{
           Class.forName("com.mysql.jdbc.Driver");
             Connection coon= DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
            Statement stmtt = coon.createStatement();
          ResultSet rst = stmtt.executeQuery("select sum(price)from bill,orders o where o.Phone_Number="+phno.getText()+";");
            int b=0;

            while(rst.next()){
                b = rst.getInt("sum(price)");

                Buy.setEnabled(true);
            }
               jTextField1.setText(""+ b);
                tax.setText(""+18+"%");
             ta=b+(b*18/100);
                total.setText(" "+ta);

        }

        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }

                                            /**/

           try{
           Class.forName("com.mysql.jdbc.Driver");
        Connection cctton= DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
            Statement sttttmt = cctton.createStatement();
        int rlis = sttttmt.executeUpdate("update billing set price='"+ta+"' where phn_number='"+phno.getText()+"';");

        } catch(Exception e)
       {
            JOptionPane.showMessageDialog(null, e);
        }
       

}//GEN-LAST:event_RemoveActionPerformed
 

    private void GenerateBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateBillActionPerformed
        // TODO add your handling code here:
        if(phno.getText().length()!=10){
            JOptionPane.showMessageDialog(null," PHONE NUMBER NOT VALID ");
        } else {
        DefaultTableModel tm = (DefaultTableModel)jTable1.getModel();
        jTable1.setSelectionBackground(Color.ORANGE);
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con= DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
            stmt = con.createStatement();
             rs = stmt.executeQuery("select * from bill b,orders o where o.Phone_Number='"+phno.getText()+"';");
          Date dt;
         int pri,nopp;
         String onn,phn,sno,fdm,ty,cn ,mp;
            while(rs.next()){
                sno = rs.getString("sno");
                pri = rs.getInt("price");
                fdm = rs.getString("foodname");
                ty = rs.getString("type");
                nopp=rs.getInt("no_of_person");
                phn=rs.getString("phone_number");
                cn=rs.getString("cust_name");
                mp=rs.getString("mode_of_payment");
                dt=rs.getDate("date");
                onn=rs.getString("odr_number");
                Object row[] = {onn,cn,phn,fdm,sno,ty,pri,dt,nopp,mp};
               tm.addRow(row);
            /**/
                 
               //int ta=0;
                  try{
           Class.forName("com.mysql.jdbc.Driver");
             Connection coon= DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
            Statement stmtt = coon.createStatement();
          ResultSet rst = stmtt.executeQuery("select sum(price)from bill,orders o where o.Phone_Number="+phno.getText()+";");
            int b=0;

            while(rst.next()){
                b = rst.getInt("sum(price)");

                Buy.setEnabled(true);
            }
               jTextField1.setText(""+ b);
                tax.setText(""+18+"%");
             ta=b+(b*18/100);
                total.setText(" "+ta);
               
        }

        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
               
            /**/

              try{
            Class.forName("com.mysql.jdbc.Driver");
        Connection    cton= DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
            Statement sttmt = cton.createStatement();
         int res = sttmt.executeUpdate("insert into billing values('"+dt+"' , '"+onn+"' , '"+
                    cn+"' , '"+phn+"' , '"+nopp+"' , '"+mp+"' , '"+fdm+"' , '"+ta+"');");
        

        } catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        }
         con.close();
        stmt.close();
        }

        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
             }
        }
       
}//GEN-LAST:event_GenerateBillActionPerformed

    private void BuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuyActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tm = (DefaultTableModel)jTable1.getModel();
        tm.setRowCount(0);
        JOptionPane.showMessageDialog(null,"Thank you for giving us this wonderful opportunity to serve you .\n \n      " +
                "                       !!! HAVE A NICE DAY :) !!!");
        this.dispose();
         try{
            Class.forName("com.mysql.jdbc.Driver");
        Connection    cton= DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
            Statement sttmt = cton.createStatement();
         int rls = sttmt.executeUpdate("insert into phone values('"+phno.getText()+"');");


        } catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }

        try{
            Class.forName("com.mysql.jdbc.Driver");
       con= DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
        stmt = con.createStatement();
            int mi = stmt.executeUpdate("delete from bill;");
            int ni = stmt.executeUpdate("delete from orders;");
           Final_Bill fbl=new Final_Bill();
           fbl.setVisible(true);
           this.setVisible(false);  
        } catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_BuyActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
}//GEN-LAST:event_CancelActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Welcome_Screen_ ws=new Welcome_Screen_();
        ws.setVisible(true);
        this.setVisible(false);
}//GEN-LAST:event_jButton6ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Billing_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buy;
    private javax.swing.JButton Cancel;
    private javax.swing.JButton GenerateBill;
    private javax.swing.JButton Remove;
    private javax.swing.JTextField in;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField phno;
    private javax.swing.JTextField tax;
    private javax.swing.JTextField total;
    private javax.swing.JLabel um;
    // End of variables declaration//GEN-END:variables

}
