import java.awt.Color;
import java.awt.Font;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Billing_Form1.java
 *
 * Created on Nov 18, 2017, 8:13:23 PM
 */

/**
 *
 * @author Yuvansh
 */
public class Billing_Form1 extends javax.swing.JFrame {
      Connection con = null;
Statement stmt = null;

    /** Creates new form Billing_Form1 */
    public Billing_Form1() {
        initComponents();
          try{
            Class.forName("com.mysql.jdbc.Driver");
          con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","");
        stmt= con.createStatement();
        int ros = stmt.executeUpdate("delete from bill1 where foodname='null';");
        }
             catch(Exception e)
                 {
            JOptionPane.showMessageDialog(null,e);
        }
         try{
            Class.forName("com.mysql.jdbc.Driver");
          con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","");
        stmt= con.createStatement();
         ResultSet rs = stmt.executeQuery("select fname, lname from username u ,signup s where u.uname=s.username;");
         Font font =new Font("CHILLER",Font.BOLD,30);
          while(rs.next()){
        String f = rs.getString("fname");
        String l = rs.getString("lname");
        String cm=f+"  "+l;
        um.setFont(font);
        um.setText(""+cm);
        }
         }
        catch(Exception e)
                 {
            JOptionPane.showMessageDialog(null,e);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        phno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tax = new javax.swing.JTextField();
        GenerateBill = new javax.swing.JButton();
        Buy = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        Remove = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        um = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        in = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 800));
        getContentPane().setLayout(null);
        getContentPane().add(phno);
        phno.setBounds(200, 110, 150, 20);

        jLabel7.setForeground(new java.awt.Color(0, 255, 204));
        jLabel7.setText("TOTA AMOUNT");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(370, 110, 90, 20);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(470, 100, 70, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 204));
        jLabel2.setText("Total Amount To Be Paid:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 150, 170, 20);

        jLabel3.setFont(new java.awt.Font("Raavi", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 204));
        jLabel3.setText("Rs.");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(210, 150, 30, 20);
        getContentPane().add(total);
        total.setBounds(260, 140, 90, 30);

        jLabel6.setForeground(new java.awt.Color(0, 255, 204));
        jLabel6.setText("TAX:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(550, 100, 50, 30);
        getContentPane().add(tax);
        tax.setBounds(600, 100, 40, 30);

        GenerateBill.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        GenerateBill.setText("Generate Bill");
        GenerateBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateBillActionPerformed(evt);
            }
        });
        getContentPane().add(GenerateBill);
        GenerateBill.setBounds(370, 140, 110, 30);

        Buy.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Buy.setText("Buy");
        Buy.setEnabled(false);
        Buy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyActionPerformed(evt);
            }
        });
        getContentPane().add(Buy);
        Buy.setBounds(500, 140, 100, 30);

        jTable1.setBackground(new java.awt.Color(204, 255, 204));
        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DATE", "ORDER NO.", "CUST NAME", "PHONE NO", "ADDRESS", "CITY", "LANDMARK", "FOODNAME", "ITEMCODE", "TYPE", "PRICE", "NO OF PERSON", "MODE OF PAYMENT", "MOD"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setOpaque(false);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 190, 1180, 440);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Remove Any Item :-");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(650, 90, 140, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 204));
        jLabel5.setText("Item Code :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(660, 130, 70, 15);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(750, 130, 90, 20);

        Remove.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Remove.setText("Remove");
        Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveActionPerformed(evt);
            }
        });
        getContentPane().add(Remove);
        Remove.setBounds(850, 130, 90, 23);

        Cancel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        getContentPane().add(Cancel);
        Cancel.setBounds(970, 150, 110, 23);

        jLabel8.setBackground(new java.awt.Color(204, 204, 255));
        jLabel8.setForeground(new java.awt.Color(255, 255, 204));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/471074.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 20, 200, 90);

        um.setFont(new java.awt.Font("Bell MT", 3, 18)); // NOI18N
        um.setForeground(new java.awt.Color(255, 255, 51));
        getContentPane().add(um);
        um.setBounds(440, 60, 220, 30);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon.png"))); // NOI18N
        jButton6.setToolTipText("<html><font color=\"RED\" face=\"JOKERMAN\">HOME</font></html>");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(220, 20, 50, 50);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 255, 204));
        jLabel9.setText("Item Name :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(660, 160, 70, 15);
        getContentPane().add(in);
        in.setBounds(750, 160, 190, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 204, 204));
        jLabel10.setText("CUSTOMER NAME :-");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(300, 60, 130, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 255, 204));
        jLabel11.setText("ENTER PHONE NUMBER");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 110, 160, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Glaxay_sky.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1200, 730);

        setSize(new java.awt.Dimension(1219, 772));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
int b=0;
    private void GenerateBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateBillActionPerformed
        // TODO add your handling code here:
        if(phno.getText().length()!=10){
            JOptionPane.showMessageDialog(null," PHONE NUMBER NOT VALID ");
        } else {
            DefaultTableModel tm = (DefaultTableModel)jTable1.getModel();
            jTable1.setSelectionBackground(Color.ORANGE);
            try{
                Class.forName("com.mysql.jdbc.Driver");
                con= DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
                stmt = con.createStatement();
                ResultSet rs = stmt.executeQuery("select * from bill1 b,orders1 o where o.Phone_Number='"+phno.getText()+"';");
                String onn,phn,sno,fdm,ty,cn ,mp,ad,ct,lm,md;
                 Date dt;
                  int pri,nopp;
                while(rs.next()){
                    sno = rs.getString("sno");
                    pri = rs.getInt("price");
                    fdm = rs.getString("foodname");
                    ad = rs.getString("Address");
                    ct = rs.getString("City");
                    lm = rs.getString("Landmark");
                    md = rs.getString("DELIVERY_MODE");
                    ty = rs.getString("type");
                    nopp=rs.getInt("no_of_person");
                    phn=rs.getString("phone_number");
                    cn=rs.getString("cust_name");
                    mp=rs.getString("mode_of_payment");
                    dt=rs.getDate("date");
                    onn=rs.getString("oders_no");
                    Object r[] = {dt,onn,cn,phn,ad,ct,lm,fdm,sno,ty,pri,nopp,mp,md};
                    tm.addRow(r);

                    int tot=0;
                     try{
                Class.forName("com.mysql.jdbc.Driver");
                con= DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
                stmt = con.createStatement();
                ResultSet rts = stmt.executeQuery("select sum(price)from bill1,orders1 o where o.Phone_Number="+phno.getText()+";");
                while(rts.next()){
                    b = rts.getInt("sum(price)");

                    Buy.setEnabled(true);
                }
                jTextField1.setText(""+ b);
                tax.setText(""+18+"%");
                tot=b+(b*18/100);
                total.setText(" "+tot);
            }

            catch(Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

            try{
                Class.forName("com.mysql.jdbc.Driver");
                con= DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
                stmt = con.createStatement();
                int res = stmt.executeUpdate("insert into billing1 values('"+dt+"' , '"+onn+"' , '"+
                        cn+"' , '"+phn+"' , '"+ad+"' , '"+md+"', '"+nopp+"' , '"+mp+"' , '"+fdm+"' , '"+tot+"');");
            } catch(Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

                }
            } catch(Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }

           
    }//GEN-LAST:event_GenerateBillActionPerformed

    private void BuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuyActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tm = (DefaultTableModel)jTable1.getModel();
        tm.setRowCount(0);
        JOptionPane.showMessageDialog(null,"Thank you for giving us this wonderful opportunity to serve you .\n \n      " +
                "                       !!! HAVE A NICE DAY :) !!!");
        this.dispose();

        try{
            Class.forName("com.mysql.jdbc.Driver");
        Connection    cton= DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
            Statement sttmt = cton.createStatement();
         int rls = sttmt.executeUpdate("insert into phone1 values('"+phno.getText()+"');");
        } catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }

        try{
            Class.forName("com.mysql.jdbc.Driver");
            con= DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
            stmt = con.createStatement();
                int mi = stmt.executeUpdate("delete from bill1;");
                int ni = stmt.executeUpdate("delete from orders1;");
           Final_Bill1 fbl1=new Final_Bill1();
           fbl1.setVisible(true);
           this.setVisible(false);
              stmt.close();
              con.close();                   
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
}//GEN-LAST:event_BuyActionPerformed
String on,ph,so,fnm,t,c ,m,add,cty,lmk,mod;
int p,nop;
Date d;
int a = 0;
int ta=0;
    private void RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tm = (DefaultTableModel)jTable1.getModel();

        tm.setRowCount(0);

       a = Integer.parseInt(jTextField2.getText());

          try{
           Class.forName("com.mysql.jdbc.Driver");
        Connection    ctton= DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
            Statement stttmt = ctton.createStatement();
        int rls = stttmt.executeUpdate("delete from billing1 where phone_number='"+phno.getText()+"' and item='"+in.getText()+"';");

        } catch(Exception e)
       {
            JOptionPane.showMessageDialog(null, e);
        }

                                               /**/
        try{
            Class.forName("com.mysql.jdbc.Driver");
           Connection  ccon= DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
            Statement sstmt = ccon.createStatement();
            int dtt = sstmt.executeUpdate("delete from bill1 where sno='"+a+"';");
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

                                           /**/

        try{
            Class.forName("com.mysql.jdbc.Driver");
          Connection  ccon= DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
           Statement sstmt = ccon.createStatement();
            ResultSet rs = sstmt.executeQuery("select * from bill1 b,orders1 o where o.PHONE_NUMBER ='"+phno.getText()+"';");

            while(rs.next()){
                so = rs.getString("sno");
                p = rs.getInt("price");
                fnm = rs.getString("foodname");
                 add = rs.getString("Address");
                 cty = rs.getString("City");
                 lmk = rs.getString("Landmark");
                 mod = rs.getString("DELIVERY_MODE");
                t = rs.getString("type");
                nop=rs.getInt("no_of_person");
                ph=rs.getString("phone_number");
                c=rs.getString("cust_name");
                m=rs.getString("mode_of_payment");
                d=rs.getDate("date");
                on=rs.getString("oders_no");
                Object r[] = {d,on,c,ph,add,cty,lmk,fnm,so,p,nop,m,mod};
                tm.addRow(r);}
        }
             catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

                              /**/

                
       try{
           Class.forName("com.mysql.jdbc.Driver");
             Connection coon= DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
            Statement stmtt = coon.createStatement();
          ResultSet rst = stmtt.executeQuery("select sum(price)from bill1,orders1 o where o.Phone_Number="+phno.getText()+";");
            int n=0;

            while(rst.next()){
                n = rst.getInt("sum(price)");

                Buy.setEnabled(true);
            }
               jTextField1.setText(""+ n);
                tax.setText(""+18+"%");
             ta=n+(n*18/100);
                total.setText(" "+ta);

        }

        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
                             /**/

         try{
           Class.forName("com.mysql.jdbc.Driver");
        Connection cctton= DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
            Statement sttttmt = cctton.createStatement();
        int rlis = sttttmt.executeUpdate("update billing1 set price='"+ta+"' where phone_number='"+phno.getText()+"';");

        } catch(Exception e)
       {
            JOptionPane.showMessageDialog(null, e);
        }

}//GEN-LAST:event_RemoveActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
}//GEN-LAST:event_CancelActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Welcome_Screen_ ws=new Welcome_Screen_();
        ws.setVisible(true);
        this.setVisible(false);
}//GEN-LAST:event_jButton6ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Billing_Form1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buy;
    private javax.swing.JButton Cancel;
    private javax.swing.JButton GenerateBill;
    private javax.swing.JButton Remove;
    private javax.swing.JTextField in;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField phno;
    private javax.swing.JTextField tax;
    private javax.swing.JTextField total;
    private javax.swing.JLabel um;
    // End of variables declaration//GEN-END:variables

}
