import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Order_History.java
 *
 * Created on Jul 25, 2017, 1:15:03 PM
 */

/**
 *
 * @author Yuvansh
 */
public class Cancel_Order extends javax.swing.JFrame {
  Connection con = null;
Statement stmt = null;
//ResultSet rs = null;

    /** Creates new form Order_History */
    public Cancel_Order() {
        initComponents();
    jp1.setVisible(false);
    jp2.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jp1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cant = new javax.swing.JTable();
        jp2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cant1 = new javax.swing.JTable();
        cmn = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        dlt = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        hd = new javax.swing.JRadioButton();
        po = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(915, 670));
        getContentPane().setLayout(null);

        jp1.setOpaque(false);

        cant.setBackground(new java.awt.Color(255, 204, 204));
        cant.setFont(new java.awt.Font("Corbel", 3, 14)); // NOI18N
        cant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ORDER NO.", "DATE", "CUST NAME", "PHONE", "NO OF PEOPLE", "MODE OF PAYMENT", "ITEM", "PRICE"
            }
        ));
        jScrollPane1.setViewportView(cant);

        org.jdesktop.layout.GroupLayout jp1Layout = new org.jdesktop.layout.GroupLayout(jp1);
        jp1.setLayout(jp1Layout);
        jp1Layout.setHorizontalGroup(
            jp1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jp1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 935, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jp1Layout.setVerticalGroup(
            jp1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jp1Layout.createSequentialGroup()
                .add(37, 37, 37)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jp1);
        jp1.setBounds(30, 210, 960, 490);

        jp2.setOpaque(false);

        jScrollPane2.setEnabled(false);

        cant1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ORDER NO.", "DATE", "CUST. NAME", "PHONE", "ADDRESS", "DELIVERY MODE", "NO OF PEOPLE", "MODE OF PAYMENT", "ITEM", "PRICE"
            }
        ));
        jScrollPane2.setViewportView(cant1);

        org.jdesktop.layout.GroupLayout jp2Layout = new org.jdesktop.layout.GroupLayout(jp2);
        jp2.setLayout(jp2Layout);
        jp2Layout.setHorizontalGroup(
            jp2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jp2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1110, Short.MAX_VALUE)
                .addContainerGap())
        );
        jp2Layout.setVerticalGroup(
            jp2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jp2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(jp2);
        jp2.setBounds(30, 230, 1130, 460);

        cmn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmnMouseClicked(evt);
            }
        });
        getContentPane().add(cmn);
        cmn.setBounds(240, 170, 180, 30);

        jLabel1.setFont(new java.awt.Font("AngsanaUPC", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setText("ENTER CUSTOMER NAME");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 170, 210, 30);

        dlt.setFont(new java.awt.Font("Bookman Old Style", 3, 18)); // NOI18N
        dlt.setForeground(new java.awt.Color(0, 0, 51));
        dlt.setText("DELETE");
        dlt.setEnabled(false);
        dlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dltActionPerformed(evt);
            }
        });
        getContentPane().add(dlt);
        dlt.setBounds(760, 170, 120, 31);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon.png"))); // NOI18N
        jButton6.setToolTipText("<html><font color=\"RED\" face=\"JOKERMAN\">HOME</font></html>");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(180, 20, 50, 50);

        jLabel5.setBackground(new java.awt.Color(204, 204, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/471074.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 20, 200, 92);

        jTextField2.setEnabled(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(670, 170, 60, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("Order Number :");
        jLabel6.setEnabled(false);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(540, 170, 110, 30);

        jLabel7.setFont(new java.awt.Font("Forte", 2, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 255, 255));
        jLabel7.setText("~THE OCEAN OF TASTES");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 100, 210, 20);

        jLabel3.setFont(new java.awt.Font("Algerian", 3, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CANCEL ORDER");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(240, 30, 440, 40);

        buttonGroup1.add(hd);
        hd.setText("HOME DELIVERY");
        hd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hdActionPerformed(evt);
            }
        });
        getContentPane().add(hd);
        hd.setBounds(440, 130, 120, 30);

        buttonGroup1.add(po);
        po.setText("PLACING ORDER");
        po.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poActionPerformed(evt);
            }
        });
        getContentPane().add(po);
        po.setBounds(310, 130, 120, 30);

        jLabel4.setFont(new java.awt.Font("AngsanaUPC", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 51));
        jLabel4.setText("CHOOSE YOUR ORDERING TYPE");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 130, 300, 30);

        jButton5.setText("SHOW");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(440, 180, 73, 23);

        jLabel8.setFont(new java.awt.Font("Algerian", 3, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("CANCEL ORDER");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(240, 20, 440, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ws_Windows_8_M3_1440x900.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1260, 720);

        jLabel9.setFont(new java.awt.Font("Algerian", 3, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("CANCEL ORDER");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(330, 30, 440, 40);

        setSize(new java.awt.Dimension(1279, 764));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
int a;
    private void dltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dltActionPerformed
        // TODO add your handling code here:
        if(po.isSelected()==true){
        DefaultTableModel tm = (DefaultTableModel)cant.getModel();
         tm.setRowCount(0);
         a = Integer.parseInt(jTextField2.getText());
        try{
            Class.forName("com.mysql.jdbc.Driver");
           con= DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
           stmt = con.createStatement();
            int dm = stmt.executeUpdate("delete from billing where odr_number="+ a +";");
           JOptionPane.showMessageDialog(null,"!!! RECORDS HAVE SUCCESSFULLY DELETED !!!");
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        try{
            Class.forName("com.mysql.jdbc.Driver");
             con= DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
             stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from billing where cust_name ='"+cmn.getText()+"';");
            int sn,n, pri;
            String c, i, m, d, ph;
            while(rs.next()){
                sn = rs.getInt("ODR_NUMBER");
                d=rs.getString("date");
                c=rs.getString("cust_name");
                ph=rs.getString("phn_number");
                  n=rs.getInt("no_of_people");
                   m=rs.getString("mode_of_payment");
                   pri=rs.getInt("price");
                   i=rs.getString("item");
                   Object r[] = {sn,d,c,ph,n,m,i,pri};
                  tm.addRow(r);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }}
            /**/
        else
            if(hd.isSelected()==true){
        DefaultTableModel tm = (DefaultTableModel)cant1.getModel();
         tm.setRowCount(0);
         a = Integer.parseInt(jTextField2.getText());
        try{
            Class.forName("com.mysql.jdbc.Driver");
           con= DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
           stmt = con.createStatement();
            int dm = stmt.executeUpdate("delete from billing1 where odr_no="+ a +";");
           JOptionPane.showMessageDialog(null,"!!! RECORDS HAVE SUCCESSFULLY DELETED !!!");
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        try{
            Class.forName("com.mysql.jdbc.Driver");
             con= DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
             stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from billing1 where cust_name ='"+cmn.getText()+"';");
            int sn,n, pri;
            String c, i, m, d, ars, delm, ph;
            while(rs.next()){
                sn = rs.getInt("ODR_NO");
                d=rs.getString("date");
                c=rs.getString("cust_name");
                ph=rs.getString("phone_number");
                ars =rs.getString("ADDRESS");
                delm =rs.getString("DELIVERY_MODE");
                  n=rs.getInt("no_of_people");
                   m=rs.getString("mode_of_payment");
                   pri=rs.getInt("price");
                   i=rs.getString("item");
                   Object r[] = {sn,d,c,ph,ars,delm,n,m,i,pri};
                  tm.addRow(r);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }}
}//GEN-LAST:event_dltActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Welcome_Screen_ ws=new Welcome_Screen_();
        ws.setVisible(true);
        this.setVisible(false);
}//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void cmnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmnMouseClicked
        // TODO add your handling code here:
        jButton5.setEnabled(true);
    }//GEN-LAST:event_cmnMouseClicked

    private void hdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hdActionPerformed
        // TODO add your handling code here:
        if(hd.isSelected()==true)
    jp1.setVisible(false);
    jp2.setVisible(true);
    }//GEN-LAST:event_hdActionPerformed

    private void poActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poActionPerformed
        // TODO add your handling code here:
if(po.isSelected()==true)
    jp1.setVisible(true);
    jp2.setVisible(false);
    }//GEN-LAST:event_poActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(po.isSelected()==true){
        try{
            Class.forName("com.mysql.jdbc.Driver");
        Connection ccon = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","");
        Statement sstmt= ccon.createStatement();
        String query="select * from billing where cust_name = '"+cmn.getText()+"';";
        ResultSet rrs=sstmt.executeQuery(query);
       DefaultTableModel tbl1 = (DefaultTableModel) cant.getModel();
      int i=cant.getSelectedRow();
      cant.setSelectionBackground(Color.CYAN);
      while (rrs.next()){
    String  ordn = rrs.getString("ODR_Number");
    Date    dat =  rrs.getDate("DATE");
    String  custnm = rrs.getString("CUST_NAME");
    String  phn1 = rrs.getString("PHN_NUMBER");
    String  noper = rrs.getString("NO_OF_PEOPLE");
    String  mofp = rrs.getString("MODE_OF_PAYMENT");
    String  itm = rrs.getString("ITEM");
    int     prc = rrs.getInt("PRICE");
    Object[] row={ordn, dat, custnm, phn1, noper, mofp,itm,prc};
    tbl1.addRow(row);
    i++;
   dlt.setEnabled(true);
   jTextField2.setEnabled(true);
   jLabel6.setEnabled(true);
         }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }  }
                     /**/
        else if(hd.isSelected()==true){
        try{
            Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","");
        stmt= con.createStatement();
        String query="select * from billing1 where Cust_Name = '"+cmn.getText()+"';";
        ResultSet rs=stmt.executeQuery(query);
       DefaultTableModel tbl = (DefaultTableModel) cant1.getModel();
      int i=cant1.getSelectedRow();
      cant1.setSelectionBackground(Color.CYAN);
      while (rs.next()){
    String  ordn = rs.getString("ODR_No");
    Date  dat = rs.getDate("DATE");
    String  custnm = rs.getString("CUST_NAME");
    String  phn1 = rs.getString("PHoNe_NUMBER");
    String  noper = rs.getString("NO_OF_PEOPLE");
    String  nop = rs.getString("ADDRESS");
    String  nope = rs.getString("DELIVERY_MODE");
    String  mofp = rs.getString("MODE_OF_PAYMENT");
    String  itm = rs.getString("ITEM");
    int     prc = rs.getInt("PRICE");
    Object[] row={ordn, dat, custnm, phn1,nop, nope, noper, mofp,itm,prc};
    tbl.addRow(row);
    i++;
   dlt.setEnabled(true);
   jTextField2.setEnabled(true);
   jLabel6.setEnabled(true);
         }
      rs.close();
      stmt.close();
      con.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }  }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cancel_Order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTable cant;
    private javax.swing.JTable cant1;
    private javax.swing.JTextField cmn;
    private javax.swing.JButton dlt;
    private javax.swing.JRadioButton hd;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel jp1;
    private javax.swing.JPanel jp2;
    private javax.swing.JRadioButton po;
    // End of variables declaration//GEN-END:variables

}
