/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Contact_Us.java
 *
 * Created on Oct 10, 2017, 8:13:49 PM
 */

/**
 *
 * @author Yuvansh
 */
public class Contact_Us extends javax.swing.JFrame {

    /** Creates new form Contact_Us */
    public Contact_Us() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(640, 620));
        getContentPane().setLayout(null);

        jLabel5.setBackground(new java.awt.Color(204, 204, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/471074.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(310, 470, 200, 70);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon.png"))); // NOI18N
        jButton6.setToolTipText("<html><font color=\"RED\" face=\"JOKERMAN\">HOME</font></html>");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(40, 20, 50, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Man.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 150, 60, 60);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/woman.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(200, 60, 60, 60);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/woman 2.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(370, 150, 70, 61);

        jLabel6.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("YOGESH SINGH");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(170, 210, 120, 20);

        jLabel7.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("GARGI SHARMA");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(350, 210, 110, 20);

        jLabel8.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("MILI RATHOR");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(180, 120, 110, 20);

        jLabel9.setFont(new java.awt.Font("Dotum", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 153, 0));
        jLabel9.setText(" www.garnish.com");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(170, 500, 160, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/social-media-icons - Copy (2).png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(160, 290, 45, 40);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/social-media-icons - Copy (3).png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(220, 290, 45, 40);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/social-media-icons.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(290, 290, 45, 40);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/social-media-icons - Copy.png"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(350, 290, 45, 42);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/social-media-icons - Copy (4).png"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(410, 290, 45, 40);

        jLabel15.setFont(new java.awt.Font("Dotum", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 153, 0));
        jLabel15.setText(" Mumbai , Maharastra");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(170, 420, 150, 30);

        jLabel17.setFont(new java.awt.Font("Century", 3, 24)); // NOI18N
        jLabel17.setText("CONTACT US");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(320, 360, 200, 40);

        jLabel18.setFont(new java.awt.Font("Dotum", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 153, 0));
        jLabel18.setText(" 9654328530");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(170, 475, 90, 30);

        jLabel19.setFont(new java.awt.Font("Dotum", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 153, 0));
        jLabel19.setText(" garnish0808@gmail.com");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(170, 450, 160, 30);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Man.jpg"))); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(370, 60, 60, 60);

        jLabel20.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("YUVANSH JOSHI");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(340, 120, 120, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/card.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 630, 580);

        setSize(new java.awt.Dimension(645, 621));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Welcome_Screen_ ws=new Welcome_Screen_();
        ws.setVisible(true);
        this.setVisible(false);
}//GEN-LAST:event_jButton6ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contact_Us().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

}
