import java.awt.Color;
import java.awt.Font;
import java.sql.*;
import javax.swing.JOptionPane;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Feedback_Form.java
 *
 * Created on Nov 4, 2017, 2:34:31 PM
 */

/**
 *
 * @author Yuvansh
 */
public class Feedback_Form extends javax.swing.JFrame {
     Connection con= null;
Statement stmt = null;
//ResultSet r= null;

    /** Creates new form Feedback_Form */
    public Feedback_Form() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        review = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rating = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        e1 = new javax.swing.JRadioButton();
        b1 = new javax.swing.JRadioButton();
        a1 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        b3 = new javax.swing.JRadioButton();
        a2 = new javax.swing.JRadioButton();
        e2 = new javax.swing.JRadioButton();
        b2 = new javax.swing.JRadioButton();
        a3 = new javax.swing.JRadioButton();
        e3 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        b4 = new javax.swing.JRadioButton();
        a4 = new javax.swing.JRadioButton();
        e4 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1010, 600));
        getContentPane().setLayout(null);

        review.setColumns(20);
        review.setFont(new java.awt.Font("Harlow Solid Italic", 2, 18)); // NOI18N
        review.setForeground(new java.awt.Color(102, 102, 102));
        review.setLineWrap(true);
        review.setRows(5);
        review.setText("*Max. 100  Alphabets");
        review.setWrapStyleWord(true);
        review.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(102, 102, 102), new java.awt.Color(51, 51, 51), new java.awt.Color(153, 153, 153)));
        review.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reviewMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reviewMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                reviewMouseReleased(evt);
            }
        });
        review.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                reviewMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                reviewMouseMoved(evt);
            }
        });
        review.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                reviewFocusLost(evt);
            }
        });
        review.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                reviewKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(review);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(620, 400, 260, 130);

        jLabel3.setFont(new java.awt.Font("Jokerman", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("PHONE NUMBER");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 160, 190, 29);

        jLabel2.setFont(new java.awt.Font("Jokerman", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("NAME");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 110, 190, 30);

        jLabel4.setFont(new java.awt.Font("Jokerman", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("RATINGS");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 400, 190, 32);

        jLabel5.setFont(new java.awt.Font("Calisto MT", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("/  10");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(340, 400, 70, 30);
        getContentPane().add(rating);
        rating.setBounds(270, 400, 60, 30);

        name.setForeground(new java.awt.Color(102, 102, 102));
        name.setText("FULL NAME (OPTIONAL)");
        name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameMouseClicked(evt);
            }
        });
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameFocusLost(evt);
            }
        });
        getContentPane().add(name);
        name.setBounds(240, 110, 260, 30);

        jLabel6.setForeground(new java.awt.Color(255, 204, 51));
        jLabel6.setText("* mandatory");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 430, 70, 20);
        getContentPane().add(phone);
        phone.setBounds(240, 160, 260, 30);

        jLabel7.setFont(new java.awt.Font("Jokerman", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("REVIEW");
        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(450, 400, 150, 30);

        jLabel8.setBackground(new java.awt.Color(204, 204, 255));
        jLabel8.setForeground(new java.awt.Color(255, 255, 204));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/471074.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 10, 200, 90);

        e1.setBackground(new java.awt.Color(204, 255, 255));
        buttonGroup1.add(e1);
        e1.setFont(new java.awt.Font("Monotype Corsiva", 1, 14)); // NOI18N
        e1.setForeground(new java.awt.Color(255, 102, 0));
        e1.setText("EXCELLENT");
        e1.setFocusPainted(false);
        getContentPane().add(e1);
        e1.setBounds(40, 340, 130, 30);

        b1.setBackground(new java.awt.Color(204, 255, 255));
        buttonGroup1.add(b1);
        b1.setFont(new java.awt.Font("Monotype Corsiva", 1, 14)); // NOI18N
        b1.setForeground(new java.awt.Color(255, 102, 0));
        b1.setText("BAD");
        b1.setFocusPainted(false);
        getContentPane().add(b1);
        b1.setBounds(40, 260, 90, 30);

        a1.setBackground(new java.awt.Color(204, 255, 255));
        buttonGroup1.add(a1);
        a1.setFont(new java.awt.Font("Monotype Corsiva", 1, 14)); // NOI18N
        a1.setForeground(new java.awt.Color(255, 102, 0));
        a1.setText("AVERAGE");
        a1.setFocusPainted(false);
        a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1ActionPerformed(evt);
            }
        });
        getContentPane().add(a1);
        a1.setBounds(40, 300, 110, 30);

        jLabel10.setFont(new java.awt.Font("Jokerman", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 0));
        jLabel10.setText("QUAITY OF FOOD");
        jLabel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel10);
        jLabel10.setBounds(270, 210, 190, 30);

        jLabel11.setFont(new java.awt.Font("Jokerman", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 0));
        jLabel11.setText("CLEANLINESS");
        jLabel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel11);
        jLabel11.setBounds(510, 210, 190, 30);

        b3.setBackground(new java.awt.Color(204, 255, 255));
        buttonGroup3.add(b3);
        b3.setFont(new java.awt.Font("Monotype Corsiva", 1, 14)); // NOI18N
        b3.setForeground(new java.awt.Color(255, 102, 0));
        b3.setText("BAD");
        b3.setFocusPainted(false);
        getContentPane().add(b3);
        b3.setBounds(510, 260, 90, 30);

        a2.setBackground(new java.awt.Color(204, 255, 255));
        buttonGroup2.add(a2);
        a2.setFont(new java.awt.Font("Monotype Corsiva", 1, 14)); // NOI18N
        a2.setForeground(new java.awt.Color(255, 102, 0));
        a2.setText("AVERAGE");
        a2.setFocusPainted(false);
        getContentPane().add(a2);
        a2.setBounds(270, 290, 110, 30);

        e2.setBackground(new java.awt.Color(204, 255, 255));
        buttonGroup2.add(e2);
        e2.setFont(new java.awt.Font("Monotype Corsiva", 1, 14)); // NOI18N
        e2.setForeground(new java.awt.Color(255, 102, 0));
        e2.setText("EXCELLENT");
        e2.setFocusPainted(false);
        e2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e2ActionPerformed(evt);
            }
        });
        getContentPane().add(e2);
        e2.setBounds(270, 340, 130, 30);

        b2.setBackground(new java.awt.Color(204, 255, 255));
        buttonGroup2.add(b2);
        b2.setFont(new java.awt.Font("Monotype Corsiva", 1, 14)); // NOI18N
        b2.setForeground(new java.awt.Color(255, 102, 0));
        b2.setText("BAD");
        b2.setFocusPainted(false);
        getContentPane().add(b2);
        b2.setBounds(270, 250, 90, 30);

        a3.setBackground(new java.awt.Color(204, 255, 255));
        buttonGroup3.add(a3);
        a3.setFont(new java.awt.Font("Monotype Corsiva", 1, 14)); // NOI18N
        a3.setForeground(new java.awt.Color(255, 102, 0));
        a3.setText("AVERAGE");
        a3.setFocusPainted(false);
        a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a3ActionPerformed(evt);
            }
        });
        getContentPane().add(a3);
        a3.setBounds(510, 300, 110, 30);

        e3.setBackground(new java.awt.Color(204, 255, 255));
        buttonGroup3.add(e3);
        e3.setFont(new java.awt.Font("Monotype Corsiva", 1, 14)); // NOI18N
        e3.setForeground(new java.awt.Color(255, 102, 0));
        e3.setText("EXCELLENT");
        e3.setFocusPainted(false);
        getContentPane().add(e3);
        e3.setBounds(510, 340, 130, 30);

        jLabel12.setFont(new java.awt.Font("Jokerman", 3, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 0));
        jLabel12.setText("RESPONSE TIME");
        jLabel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel12);
        jLabel12.setBounds(750, 210, 190, 30);

        b4.setBackground(new java.awt.Color(204, 255, 255));
        buttonGroup4.add(b4);
        b4.setFont(new java.awt.Font("Monotype Corsiva", 1, 14)); // NOI18N
        b4.setForeground(new java.awt.Color(255, 102, 0));
        b4.setText("BAD");
        b4.setFocusPainted(false);
        getContentPane().add(b4);
        b4.setBounds(750, 260, 90, 30);

        a4.setBackground(new java.awt.Color(204, 255, 255));
        buttonGroup4.add(a4);
        a4.setFont(new java.awt.Font("Monotype Corsiva", 1, 14)); // NOI18N
        a4.setForeground(new java.awt.Color(255, 102, 0));
        a4.setText("AVERAGE");
        a4.setFocusPainted(false);
        a4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a4ActionPerformed(evt);
            }
        });
        getContentPane().add(a4);
        a4.setBounds(750, 300, 110, 30);

        e4.setBackground(new java.awt.Color(204, 255, 255));
        buttonGroup4.add(e4);
        e4.setFont(new java.awt.Font("Monotype Corsiva", 1, 14)); // NOI18N
        e4.setForeground(new java.awt.Color(255, 102, 0));
        e4.setText("EXCELLENT");
        e4.setFocusPainted(false);
        getContentPane().add(e4);
        e4.setBounds(750, 340, 130, 30);

        jLabel9.setFont(new java.awt.Font("Jokerman", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 0));
        jLabel9.setText("SERVICE");
        jLabel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 210, 190, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Submit-Button-PNG-Clipart.png"))); // NOI18N
        jButton1.setToolTipText("<html><font color=\"RED\" face=\"JOKERMAN\">SUBMIT</font></html>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(290, 470, 150, 40);

        jLabel13.setFont(new java.awt.Font("Harrington", 3, 48)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 204, 0));
        jLabel13.setText("FEEDBACK  FORM");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(290, 20, 540, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nature-landscape-Houses-river-sunset-forest-trees-birds-Wallpapers-HD-2560x1600-1366x768.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 560);

        setSize(new java.awt.Dimension(1019, 602));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_a1ActionPerformed

    private void e2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e2ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_e2ActionPerformed

    private void a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a3ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_a3ActionPerformed

    private void a4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a4ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_a4ActionPerformed
String fd1,fd2,fd3,fd4;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(phone.getText().length()!=10||name.getText().equals("")||rating.getText().equals("")||review.getText().length()>101){
             JOptionPane.showMessageDialog(null,"PLEASE FILL THE DETAILS CAREFULLY X(");
        } else{
            String n = name.getText();
            String p = phone.getText();
            int rat = Integer.parseInt(rating.getText());
            String rev = review.getText();
            String bad=b1.getText();
            if(b1.isSelected()==true){
            fd1="BAD";
            }
            if(a1.isSelected()==true){
            fd1="AVERAGE";
            }
            if(e1.isSelected()==true){
            fd1="EXCELLENT";
            }

            if(b2.isSelected()==true){
            fd2="BAD";
            }
            if(a2.isSelected()==true){
            fd2="AVERAGE";
            }
            if(e2.isSelected()==true){
            fd2="EXCELLENT";
            }

            if(b3.isSelected()==true){
            fd3="BAD";
            }
            if(a3.isSelected()==true){
            fd3="AVERAGE";
            }
            if(e3.isSelected()==true){
            fd3="EXCELLENT";
            }

            if(b4.isSelected()==true){
            fd4="BAD";
            }
            if(a4.isSelected()==true){
            fd4="AVERAGE";
            }
            if(e4.isSelected()==true){
            fd4="EXCELLENT";
            }
            
             try{
            Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","");
       stmt = con.createStatement();
       String query="insert into feedback values("+" ' "+n+"' , '"+p+"' , '"+fd1+"' , '"+fd2+"' , '"+fd3+"' , '"+fd4+"' , '"+rev+"' , "+rat+");";
        int rs = stmt.executeUpdate(query);
            
        String show = "!!! THANK YOU FOR YOUR KIND FEEDBACK !!! \n \n           " +" HOPE YOU ENJOYED OUR SERVICES :)  "    ;
                            JOptionPane.showMessageDialog(null,show);

                            Welcome_Screen_ ws=new Welcome_Screen_();
                          ws.setVisible(true);
                           this.setVisible(false);
             }
             catch(Exception e)
       {
           JOptionPane.showMessageDialog(null,e);
       }
        }

         

    }//GEN-LAST:event_jButton1ActionPerformed

    private void reviewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reviewMouseClicked
        // TODO add your handling code here:
        review.setText("");
        Font font = new Font("MONOTYPE CORSIVA",Font.ITALIC,20);
        review.setFont(font);
        review.setForeground(Color.BLACK);
    }//GEN-LAST:event_reviewMouseClicked

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nameActionPerformed

    private void nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameMouseClicked
        // TODO add your handling code here:
        name.setText("");
        name.setForeground(Color.BLACK);
         
    }//GEN-LAST:event_nameMouseClicked

    private void reviewKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reviewKeyPressed
        // TODO add your handling code here:
        if(review.getText().length()>101){    
        JOptionPane.showMessageDialog(null,"WORD LIMIT EXCEED");
        }

    }//GEN-LAST:event_reviewKeyPressed

    private void reviewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reviewMouseExited
        // TODO add your handling code here:
       
    }//GEN-LAST:event_reviewMouseExited

    private void reviewMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reviewMouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_reviewMouseReleased

    private void reviewMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reviewMouseDragged
        // TODO add your handling code here:

    }//GEN-LAST:event_reviewMouseDragged

    private void reviewMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reviewMouseMoved
        // TODO add your handling code here:

    }//GEN-LAST:event_reviewMouseMoved

    private void reviewFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_reviewFocusLost
        // TODO add your handling code here:
        if(review.getText().equals("")){
             review.setText("*Max. 100 Alphabets");
        Font font = new Font("HARLOW SOLID ITALIC",Font.ITALIC,18);
        review.setFont(font);
        review.setForeground(Color.GRAY);
        } 
    }//GEN-LAST:event_reviewFocusLost

    private void nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFocusGained

    private void nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusLost
        // TODO add your handling code here:
        if(name.getText().equals("")){
          name.setText("FULL NAME (OPTIONAL)");
        name.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_nameFocusLost

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Feedback_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton a1;
    private javax.swing.JRadioButton a2;
    private javax.swing.JRadioButton a3;
    private javax.swing.JRadioButton a4;
    private javax.swing.JRadioButton b1;
    private javax.swing.JRadioButton b2;
    private javax.swing.JRadioButton b3;
    private javax.swing.JRadioButton b4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JRadioButton e1;
    private javax.swing.JRadioButton e2;
    private javax.swing.JRadioButton e3;
    private javax.swing.JRadioButton e4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField rating;
    private javax.swing.JTextArea review;
    // End of variables declaration//GEN-END:variables

}
