import java.sql.*;
import javax.swing.JOptionPane;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Final_Bill.java
 *
 * Created on Nov 23, 2017, 11:09:40 PM
 */

/**
 *
 * @author Yuvansh
 */
public class Final_Bill extends javax.swing.JFrame {
    Connection con=null;
    Statement stmt=null;
    ResultSet rs=null;

    /** Creates new form Final_Bill */
    public Final_Bill() {
        initComponents();
        fi.setCaretPosition(0);
        try{
            Class.forName("com.mysql.jdbc.Driver");
        Connection    cton= DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
            Statement sttmt = cton.createStatement();
       rs = sttmt.executeQuery("Select * from phone;");
   while(rs.next()){
         String pt=rs.getString("pn");
         pn.setText(""+pt);
   }
        } catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
         try{
            Class.forName("com.mysql.jdbc.Driver");
             con= DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
            stmt = con.createStatement();
             rs = stmt.executeQuery("select * from billing where phn_number='"+pn.getText()+"';");

            while(rs.next()){
               int pri = rs.getInt("price");
               int nopp=rs.getInt("no_of_people");
               String  phn=rs.getString("phn_number");
               String  cn=rs.getString("cust_name");
               String  mp=rs.getString("mode_of_payment");
               Date dt=rs.getDate("date");
               String  onn=rs.getString("odr_number");

              da.setText(""+dt);
              tamt.setText(""+pri);
              nopl.setText(""+nopp);
              pn.setText(""+phn);
              cu.setText(""+cn);
              mopy.setText(""+mp);
              orn.setText(""+onn);
            }
         }
          catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        /**/
        int n=1;
        try{
            Class.forName("com.mysql.jdbc.Driver");
             con= DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
            stmt = con.createStatement();
            rs = stmt.executeQuery("select item from billing where phn_number ='"+pn.getText()+"';");

            while(rs.next()){
            String i=rs.getString("item");
            fi.append("\n"+n++ +"  "+i+"\n");
            }
         }
          catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        da = new javax.swing.JTextField();
        cu = new javax.swing.JTextField();
        pn = new javax.swing.JTextField();
        mopy = new javax.swing.JTextField();
        tamt = new javax.swing.JTextField();
        nopl = new javax.swing.JTextField();
        orn = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        fi = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(720, 620));
        getContentPane().setLayout(null);

        jLabel8.setBackground(new java.awt.Color(204, 204, 255));
        jLabel8.setForeground(new java.awt.Color(255, 255, 204));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/471074.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 10, 200, 90);

        jLabel2.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("NO OF PEOPLE");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 300, 190, 30);

        jLabel3.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("ORDER NUMBER");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 180, 190, 30);

        jLabel4.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("DATE");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 140, 190, 30);

        jLabel5.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("CUSTOMER NAME");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 220, 190, 30);

        jLabel6.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("PHONE NUMBER");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 260, 190, 30);

        jLabel7.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("MODE OF PAYMENT");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(80, 350, 190, 20);

        jLabel9.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 0));
        jLabel9.setText("TOTAL AMOUNT");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(80, 530, 190, 30);

        jLabel10.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 0));
        jLabel10.setText("FOOD ITEMS");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(80, 410, 190, 30);

        da.setEditable(false);
        da.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daActionPerformed(evt);
            }
        });
        getContentPane().add(da);
        da.setBounds(340, 140, 160, 30);

        cu.setEditable(false);
        getContentPane().add(cu);
        cu.setBounds(340, 220, 160, 30);

        pn.setEditable(false);
        getContentPane().add(pn);
        pn.setBounds(340, 260, 160, 30);

        mopy.setEditable(false);
        getContentPane().add(mopy);
        mopy.setBounds(340, 340, 160, 30);

        tamt.setEditable(false);
        getContentPane().add(tamt);
        tamt.setBounds(340, 530, 160, 30);

        nopl.setEditable(false);
        getContentPane().add(nopl);
        nopl.setBounds(340, 300, 160, 30);

        orn.setEditable(false);
        orn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ornActionPerformed(evt);
            }
        });
        getContentPane().add(orn);
        orn.setBounds(340, 180, 160, 30);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon.png"))); // NOI18N
        jButton6.setToolTipText("<html><font color=\"RED\" face=\"JOKERMAN\">HOME</font></html>");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(200, 20, 50, 50);

        fi.setColumns(20);
        fi.setEditable(false);
        fi.setLineWrap(true);
        fi.setRows(5);
        fi.setWrapStyleWord(true);
        jScrollPane2.setViewportView(fi);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(340, 390, 160, 130);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo-cloud-solutions-background-5.jpg"))); // NOI18N
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 710, 580);

        setSize(new java.awt.Dimension(729, 621));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ornActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ornActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
       int dialogButton = JOptionPane.YES_NO_OPTION;
          int o= JOptionPane.showConfirmDialog(null,"WANNA GIVE FEEDBACK","FEEDBACK",dialogButton);
             if(o == JOptionPane.YES_OPTION){
                 try{
            Class.forName("com.mysql.jdbc.Driver");
          con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","");
        stmt= con.createStatement();
        int ros = stmt.executeUpdate("delete from phone where pn='"+pn.getText()+"';");
        }
             catch(Exception e)
                 {
            JOptionPane.showMessageDialog(null,e);
        }
           Feedback_Form ff=new Feedback_Form();
           ff.setVisible(true);
           this.setVisible(false);
             } else
          if(o == JOptionPane.NO_OPTION){
                     try{
            Class.forName("com.mysql.jdbc.Driver");
          con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","");
        stmt= con.createStatement();
        int ros = stmt.executeUpdate("delete from phone where pn='"+pn.getText()+"';");
        }
             catch(Exception e)
                 {
            JOptionPane.showMessageDialog(null,e);
        }
        Welcome_Screen_ ws=new Welcome_Screen_();
        ws.setVisible(true);
        this.setVisible(false);
          }
}//GEN-LAST:event_jButton6ActionPerformed

    private void daActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_daActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Final_Bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cu;
    private javax.swing.JTextField da;
    private javax.swing.JTextArea fi;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField mopy;
    private javax.swing.JTextField nopl;
    private javax.swing.JTextField orn;
    private javax.swing.JTextField pn;
    private javax.swing.JTextField tamt;
    // End of variables declaration//GEN-END:variables

}
