import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Home_Delivery.java
 *
 * Created on Aug 5, 2017, 8:26:02 PM
 */

/**
 *
 * @author Yuvansh
 */
public class Home_Delivery extends javax.swing.JFrame {
    Connection con = null;
Statement stmt = null;
ResultSet rs= null;
int icode, p;
String fdname,t;

    /** Creates new form Home_Delivery */
    public Home_Delivery() {
        initComponents();
         try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
        stmt= con.createStatement();

      //  rs.close();
       // stmt.close();
      //  con.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jButton70 = new javax.swing.JButton();
        jButton71 = new javax.swing.JButton();
        jButton72 = new javax.swing.JButton();
        jButton73 = new javax.swing.JButton();
        jButton74 = new javax.swing.JButton();
        jButton75 = new javax.swing.JButton();
        jButton76 = new javax.swing.JButton();
        jButton77 = new javax.swing.JButton();
        jButton78 = new javax.swing.JButton();
        jButton79 = new javax.swing.JButton();
        jButton80 = new javax.swing.JButton();
        jButton81 = new javax.swing.JButton();
        jButton82 = new javax.swing.JButton();
        jButton83 = new javax.swing.JButton();
        jButton84 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        q1 = new javax.swing.JTextField();
        q2 = new javax.swing.JTextField();
        q3 = new javax.swing.JTextField();
        q4 = new javax.swing.JTextField();
        q5 = new javax.swing.JTextField();
        q6 = new javax.swing.JTextField();
        q7 = new javax.swing.JTextField();
        q8 = new javax.swing.JTextField();
        q9 = new javax.swing.JTextField();
        q10 = new javax.swing.JTextField();
        q15 = new javax.swing.JTextField();
        q14 = new javax.swing.JTextField();
        q13 = new javax.swing.JTextField();
        q12 = new javax.swing.JTextField();
        q11 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        date = new javax.swing.JComboBox();
        month = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        year = new javax.swing.JComboBox();
        jLabel26 = new javax.swing.JLabel();
        on = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        noc = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        phn = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        nop = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        ca = new javax.swing.JRadioButton();
        cc = new javax.swing.JRadioButton();
        dc = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton69 = new javax.swing.JButton();
        jButton85 = new javax.swing.JButton();
        jButton86 = new javax.swing.JButton();
        jButton87 = new javax.swing.JButton();
        jButton88 = new javax.swing.JButton();
        jButton89 = new javax.swing.JButton();
        jButton90 = new javax.swing.JButton();
        jButton91 = new javax.swing.JButton();
        jButton92 = new javax.swing.JButton();
        jButton93 = new javax.swing.JButton();
        jButton94 = new javax.swing.JButton();
        jButton95 = new javax.swing.JButton();
        jButton96 = new javax.swing.JButton();
        jButton97 = new javax.swing.JButton();
        jButton98 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        jLabel33 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        pincode = new javax.swing.JTextField();
        landmark = new javax.swing.JTextField();
        city = new javax.swing.JComboBox();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        fast = new javax.swing.JRadioButton();
        normal = new javax.swing.JRadioButton();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1164, 700));
        getContentPane().setLayout(null);

        jButton70.setBackground(new java.awt.Color(204, 255, 204));
        jButton70.setText("Add");
        jButton70.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton70ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton70);
        jButton70.setBounds(230, 440, 60, 23);

        jButton71.setBackground(new java.awt.Color(204, 255, 204));
        jButton71.setText("Add");
        jButton71.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton71ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton71);
        jButton71.setBounds(230, 470, 60, 23);

        jButton72.setBackground(new java.awt.Color(204, 255, 204));
        jButton72.setText("Add ");
        jButton72.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton72ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton72);
        jButton72.setBounds(230, 500, 60, 23);

        jButton73.setBackground(new java.awt.Color(204, 255, 204));
        jButton73.setText("Add ");
        jButton73.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton73ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton73);
        jButton73.setBounds(230, 530, 60, 23);

        jButton74.setBackground(new java.awt.Color(204, 255, 204));
        jButton74.setText("Add ");
        jButton74.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton74ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton74);
        jButton74.setBounds(230, 560, 60, 23);

        jButton75.setBackground(new java.awt.Color(204, 255, 204));
        jButton75.setText("Add ");
        jButton75.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton75ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton75);
        jButton75.setBounds(620, 440, 60, 23);

        jButton76.setBackground(new java.awt.Color(204, 255, 204));
        jButton76.setText("Add ");
        jButton76.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton76ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton76);
        jButton76.setBounds(620, 470, 60, 23);

        jButton77.setBackground(new java.awt.Color(204, 255, 204));
        jButton77.setText("Add ");
        jButton77.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton77ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton77);
        jButton77.setBounds(620, 500, 60, 23);

        jButton78.setBackground(new java.awt.Color(204, 255, 204));
        jButton78.setText("Add ");
        jButton78.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton78ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton78);
        jButton78.setBounds(620, 530, 60, 23);

        jButton79.setBackground(new java.awt.Color(204, 255, 204));
        jButton79.setText("Add ");
        jButton79.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton79ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton79);
        jButton79.setBounds(620, 560, 60, 23);

        jButton80.setBackground(new java.awt.Color(204, 255, 204));
        jButton80.setText("Add ");
        jButton80.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton80ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton80);
        jButton80.setBounds(990, 440, 60, 23);

        jButton81.setBackground(new java.awt.Color(204, 255, 204));
        jButton81.setText("Add ");
        jButton81.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton81ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton81);
        jButton81.setBounds(990, 470, 60, 23);

        jButton82.setBackground(new java.awt.Color(204, 255, 204));
        jButton82.setText("Add ");
        jButton82.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton82ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton82);
        jButton82.setBounds(990, 500, 60, 23);

        jButton83.setBackground(new java.awt.Color(204, 255, 204));
        jButton83.setText("Add ");
        jButton83.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton83ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton83);
        jButton83.setBounds(990, 530, 60, 23);

        jButton84.setBackground(new java.awt.Color(204, 255, 204));
        jButton84.setText("Add ");
        jButton84.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton84ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton84);
        jButton84.setBounds(990, 560, 60, 23);

        jLabel20.setFont(new java.awt.Font("Chiller", 3, 48)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("STARTER");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(140, 350, 180, 40);

        jLabel21.setFont(new java.awt.Font("Chiller", 3, 48)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("JUICES");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(510, 350, 160, 40);

        jLabel22.setFont(new java.awt.Font("Chiller", 3, 48)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("BEVERAES");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(840, 350, 210, 40);

        jLabel2.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("MEXICAN SIZZLER");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 470, 140, 20);

        jLabel3.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("VEG. CHEESE BURGER");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 500, 160, 20);

        jLabel4.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("FRENCH FRIES");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 530, 140, 20);

        jLabel5.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("VEG SANDWHICH");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 560, 140, 20);

        jLabel6.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("HOT COFFEE");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(780, 440, 140, 20);

        jLabel7.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("COLD COFFEE ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(780, 470, 140, 20);

        jLabel8.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("STRAWBERRY SHAKE");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(780, 500, 140, 20);

        jLabel9.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 0));
        jLabel9.setText("MIX FRUIT SHAKE");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(780, 530, 140, 20);

        jLabel10.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 0));
        jLabel10.setText("MANGO SHAKE");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(780, 560, 140, 20);

        jLabel11.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 0));
        jLabel11.setText("DUTCHES OF WINDSTAR");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(390, 440, 180, 20);

        jLabel12.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 0));
        jLabel12.setText("FLOSBERRY FLOB");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(390, 470, 140, 20);

        jLabel13.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 0));
        jLabel13.setText("SWEET LIME");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(390, 500, 140, 20);

        jLabel14.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 0));
        jLabel14.setText("APPLE");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(390, 530, 140, 20);

        jLabel15.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 0));
        jLabel15.setText("PINEAPPLE");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(390, 560, 140, 20);

        jLabel16.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 0));
        jLabel16.setText("DRY MANCHURIAN");
        jLabel16.setToolTipText("<html><img src=\"C:\\Users\\Yuvansh\\Documents\\NetBeansProjects\\Class_IP_Project\\src\\1036_-_Cancel_Order-512.png\"></html>");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(10, 440, 140, 20);

        jLabel17.setBackground(new java.awt.Color(255, 204, 204));
        jLabel17.setFont(new java.awt.Font("Chiller", 3, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 51));
        jLabel17.setText("ITEM NAME");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(10, 400, 90, 20);

        jLabel18.setBackground(new java.awt.Color(255, 204, 204));
        jLabel18.setFont(new java.awt.Font("Chiller", 3, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 51));
        jLabel18.setText("REMOVE ");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(310, 390, 70, 22);

        jLabel19.setBackground(new java.awt.Color(255, 204, 204));
        jLabel19.setFont(new java.awt.Font("Chiller", 3, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 51));
        jLabel19.setText("QTY.");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(180, 400, 40, 20);

        q1.setBackground(new java.awt.Color(255, 204, 204));
        q1.setFont(new java.awt.Font("High Tower Text", 3, 18)); // NOI18N
        q1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1ActionPerformed(evt);
            }
        });
        getContentPane().add(q1);
        q1.setBounds(170, 440, 50, 28);

        q2.setBackground(new java.awt.Color(255, 204, 204));
        q2.setFont(new java.awt.Font("High Tower Text", 3, 18)); // NOI18N
        getContentPane().add(q2);
        q2.setBounds(170, 470, 50, 28);

        q3.setBackground(new java.awt.Color(255, 204, 204));
        q3.setFont(new java.awt.Font("High Tower Text", 3, 18)); // NOI18N
        q3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3ActionPerformed(evt);
            }
        });
        getContentPane().add(q3);
        q3.setBounds(170, 500, 50, 28);

        q4.setBackground(new java.awt.Color(255, 204, 204));
        q4.setFont(new java.awt.Font("High Tower Text", 3, 18)); // NOI18N
        getContentPane().add(q4);
        q4.setBounds(170, 530, 50, 28);

        q5.setBackground(new java.awt.Color(255, 204, 204));
        q5.setFont(new java.awt.Font("High Tower Text", 3, 18)); // NOI18N
        getContentPane().add(q5);
        q5.setBounds(170, 560, 50, 28);

        q6.setBackground(new java.awt.Color(255, 204, 204));
        q6.setFont(new java.awt.Font("High Tower Text", 3, 18)); // NOI18N
        q6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q6ActionPerformed(evt);
            }
        });
        getContentPane().add(q6);
        q6.setBounds(560, 440, 50, 28);

        q7.setBackground(new java.awt.Color(255, 204, 204));
        q7.setFont(new java.awt.Font("High Tower Text", 3, 18)); // NOI18N
        getContentPane().add(q7);
        q7.setBounds(560, 470, 50, 28);

        q8.setBackground(new java.awt.Color(255, 204, 204));
        q8.setFont(new java.awt.Font("High Tower Text", 3, 18)); // NOI18N
        getContentPane().add(q8);
        q8.setBounds(560, 500, 50, 28);

        q9.setBackground(new java.awt.Color(255, 204, 204));
        q9.setFont(new java.awt.Font("High Tower Text", 3, 18)); // NOI18N
        getContentPane().add(q9);
        q9.setBounds(560, 530, 50, 28);

        q10.setBackground(new java.awt.Color(255, 204, 204));
        q10.setFont(new java.awt.Font("High Tower Text", 3, 18)); // NOI18N
        getContentPane().add(q10);
        q10.setBounds(560, 560, 50, 28);

        q15.setBackground(new java.awt.Color(255, 204, 204));
        q15.setFont(new java.awt.Font("High Tower Text", 3, 18)); // NOI18N
        getContentPane().add(q15);
        q15.setBounds(930, 560, 50, 28);

        q14.setBackground(new java.awt.Color(255, 204, 204));
        q14.setFont(new java.awt.Font("High Tower Text", 3, 18)); // NOI18N
        getContentPane().add(q14);
        q14.setBounds(930, 530, 50, 28);

        q13.setBackground(new java.awt.Color(255, 204, 204));
        q13.setFont(new java.awt.Font("High Tower Text", 3, 18)); // NOI18N
        getContentPane().add(q13);
        q13.setBounds(930, 500, 50, 28);

        q12.setBackground(new java.awt.Color(255, 204, 204));
        q12.setFont(new java.awt.Font("High Tower Text", 3, 18)); // NOI18N
        getContentPane().add(q12);
        q12.setBounds(930, 470, 50, 28);

        q11.setBackground(new java.awt.Color(255, 204, 204));
        q11.setFont(new java.awt.Font("High Tower Text", 3, 18)); // NOI18N
        getContentPane().add(q11);
        q11.setBounds(930, 440, 50, 28);

        jLabel23.setFont(new java.awt.Font("Gungsuh", 3, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 0));
        jLabel23.setText("DATE");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(10, 140, 60, 17);

        date.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });
        getContentPane().add(date);
        date.setBounds(60, 140, 40, 20);

        month.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "9", "10", "11", "12" }));
        month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthActionPerformed(evt);
            }
        });
        getContentPane().add(month);
        month.setBounds(130, 140, 40, 20);

        jLabel24.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel24.setText("-");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(110, 140, 20, 20);

        jLabel25.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel25.setText("-");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(180, 140, 20, 20);

        year.setEditable(true);
        year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2017", "2018", "2019", "2020" }));
        getContentPane().add(year);
        year.setBounds(200, 140, 80, 20);

        jLabel26.setFont(new java.awt.Font("Gungsuh", 3, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 0));
        jLabel26.setText("ORDER NUMBER");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(300, 140, 130, 30);

        on.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        on.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onActionPerformed(evt);
            }
        });
        on.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                onKeyTyped(evt);
            }
        });
        getContentPane().add(on);
        on.setBounds(440, 140, 90, 30);

        jLabel27.setFont(new java.awt.Font("Gungsuh", 3, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 0));
        jLabel27.setText("PINCODE");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(680, 240, 80, 20);

        noc.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        noc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nocActionPerformed(evt);
            }
        });
        noc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nocKeyTyped(evt);
            }
        });
        getContentPane().add(noc);
        noc.setBounds(730, 140, 140, 30);

        jLabel28.setFont(new java.awt.Font("Gungsuh", 3, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 0));
        jLabel28.setText("PHONE NUMBER");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(10, 180, 130, 30);

        phn.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        phn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phnActionPerformed(evt);
            }
        });
        phn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phnKeyTyped(evt);
            }
        });
        getContentPane().add(phn);
        phn.setBounds(150, 180, 170, 30);

        jLabel29.setFont(new java.awt.Font("Gungsuh", 3, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 0));
        jLabel29.setText("NO. OF PEOPLE");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(10, 230, 120, 17);

        nop.setBackground(new java.awt.Color(204, 255, 255));
        nop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        nop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nopActionPerformed(evt);
            }
        });
        getContentPane().add(nop);
        nop.setBounds(150, 220, 170, 30);

        jPanel5.setBackground(new java.awt.Color(255, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MODE  OF  PAYMENT", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kristen ITC", 2, 14), new java.awt.Color(255, 255, 51))); // NOI18N
        jPanel5.setOpaque(false);

        buttonGroup1.add(ca);
        ca.setFont(new java.awt.Font("Century", 3, 14)); // NOI18N
        ca.setForeground(new java.awt.Color(255, 153, 0));
        ca.setText("CASH");
        ca.setOpaque(false);

        buttonGroup1.add(cc);
        cc.setFont(new java.awt.Font("Century", 3, 14)); // NOI18N
        cc.setForeground(new java.awt.Color(255, 153, 0));
        cc.setText("CREDIT CARD");
        cc.setOpaque(false);

        buttonGroup1.add(dc);
        dc.setFont(new java.awt.Font("Century", 3, 14)); // NOI18N
        dc.setForeground(new java.awt.Color(255, 153, 0));
        dc.setText("DEBIT CARD");
        dc.setOpaque(false);
        dc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cc, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dc, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ca, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(ca, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cc, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(920, 190, 210, 130);

        jButton2.setBackground(new java.awt.Color(255, 255, 204));
        jButton2.setFont(new java.awt.Font("Bookman Old Style", 3, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 51));
        jButton2.setText("PLACE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(540, 310, 120, 30);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon.png"))); // NOI18N
        jButton6.setToolTipText("<html><font color=\"RED\" face=\"JOKERMAN\">HOME</font></html>");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(900, 130, 50, 50);

        jButton69.setBackground(new java.awt.Color(204, 255, 204));
        jButton69.setText("Remove");
        jButton69.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton69ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton69);
        jButton69.setBounds(1060, 560, 80, 23);

        jButton85.setBackground(new java.awt.Color(204, 255, 204));
        jButton85.setText("Remove");
        jButton85.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton85ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton85);
        jButton85.setBounds(1060, 530, 80, 23);

        jButton86.setBackground(new java.awt.Color(204, 255, 204));
        jButton86.setText("Remove");
        jButton86.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton86ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton86);
        jButton86.setBounds(300, 440, 80, 23);

        jButton87.setBackground(new java.awt.Color(204, 255, 204));
        jButton87.setText("Remove");
        jButton87.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton87ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton87);
        jButton87.setBounds(300, 470, 80, 23);

        jButton88.setBackground(new java.awt.Color(204, 255, 204));
        jButton88.setText("Remove");
        jButton88.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton88ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton88);
        jButton88.setBounds(300, 500, 80, 23);

        jButton89.setBackground(new java.awt.Color(204, 255, 204));
        jButton89.setText("Remove");
        jButton89.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton89ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton89);
        jButton89.setBounds(300, 530, 80, 23);

        jButton90.setBackground(new java.awt.Color(204, 255, 204));
        jButton90.setText("Remove");
        jButton90.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton90ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton90);
        jButton90.setBounds(300, 560, 80, 23);

        jButton91.setBackground(new java.awt.Color(204, 255, 204));
        jButton91.setText("Remove");
        jButton91.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton91ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton91);
        jButton91.setBounds(690, 440, 80, 23);

        jButton92.setBackground(new java.awt.Color(204, 255, 204));
        jButton92.setText("Remove");
        jButton92.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton92ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton92);
        jButton92.setBounds(690, 470, 80, 23);

        jButton93.setBackground(new java.awt.Color(204, 255, 204));
        jButton93.setText("Remove");
        jButton93.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton93ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton93);
        jButton93.setBounds(690, 500, 80, 23);

        jButton94.setBackground(new java.awt.Color(204, 255, 204));
        jButton94.setText("Remove");
        jButton94.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton94ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton94);
        jButton94.setBounds(690, 530, 80, 23);

        jButton95.setBackground(new java.awt.Color(204, 255, 204));
        jButton95.setText("Remove");
        jButton95.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton95ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton95);
        jButton95.setBounds(690, 560, 80, 23);

        jButton96.setBackground(new java.awt.Color(204, 255, 204));
        jButton96.setText("Remove");
        jButton96.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton96ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton96);
        jButton96.setBounds(1060, 440, 80, 23);

        jButton97.setBackground(new java.awt.Color(204, 255, 204));
        jButton97.setText("Remove");
        jButton97.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton97ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton97);
        jButton97.setBounds(1060, 470, 80, 23);

        jButton98.setBackground(new java.awt.Color(204, 255, 204));
        jButton98.setText("Remove");
        jButton98.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton98ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton98);
        jButton98.setBounds(1060, 500, 80, 23);

        jLabel30.setBackground(new java.awt.Color(255, 204, 204));
        jLabel30.setFont(new java.awt.Font("Chiller", 3, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 51));
        jLabel30.setText("ADD ");
        getContentPane().add(jLabel30);
        jLabel30.setBounds(250, 390, 40, 22);

        jButton1.setBackground(new java.awt.Color(255, 255, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton1.setText("REFRESH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(430, 310, 110, 30);

        jLabel31.setFont(new java.awt.Font("Gungsuh", 3, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 0));
        jLabel31.setText("ADDRESS");
        getContentPane().add(jLabel31);
        jLabel31.setBounds(330, 180, 100, 40);

        address.setColumns(20);
        address.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        address.setLineWrap(true);
        address.setRows(5);
        address.setWrapStyleWord(true);
        address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addressKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(address);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(430, 180, 230, 120);

        jLabel33.setFont(new java.awt.Font("Gungsuh", 3, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 0));
        jLabel33.setText("CITY");
        getContentPane().add(jLabel33);
        jLabel33.setBounds(680, 190, 50, 20);

        jLabel32.setFont(new java.awt.Font("Gungsuh", 3, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 0));
        jLabel32.setText("LANDMARK");
        getContentPane().add(jLabel32);
        jLabel32.setBounds(680, 290, 90, 20);

        jLabel34.setFont(new java.awt.Font("Gungsuh", 3, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 0));
        jLabel34.setText("NAME OF CUSTOMER");
        getContentPane().add(jLabel34);
        jLabel34.setBounds(550, 140, 180, 30);

        pincode.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        pincode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pincodeKeyTyped(evt);
            }
        });
        getContentPane().add(pincode);
        pincode.setBounds(760, 260, 140, 30);

        landmark.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        landmark.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                landmarkKeyTyped(evt);
            }
        });
        getContentPane().add(landmark);
        landmark.setBounds(760, 310, 140, 30);

        city.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ADIPUR", "ANJAR", "GANDHIDHAM", "BHUJ" }));
        getContentPane().add(city);
        city.setBounds(760, 200, 140, 30);

        jLabel35.setBackground(new java.awt.Color(255, 204, 204));
        jLabel35.setFont(new java.awt.Font("Chiller", 3, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 51));
        jLabel35.setText("ITEM ");
        getContentPane().add(jLabel35);
        jLabel35.setBounds(240, 410, 50, 20);

        jLabel36.setBackground(new java.awt.Color(255, 204, 204));
        jLabel36.setFont(new java.awt.Font("Chiller", 3, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 51));
        jLabel36.setText("ITEM");
        getContentPane().add(jLabel36);
        jLabel36.setBounds(310, 410, 50, 20);

        jLabel40.setBackground(new java.awt.Color(255, 204, 204));
        jLabel40.setFont(new java.awt.Font("Chiller", 3, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 51));
        jLabel40.setText("QTY.");
        getContentPane().add(jLabel40);
        jLabel40.setBounds(940, 400, 40, 20);

        jLabel42.setBackground(new java.awt.Color(255, 204, 204));
        jLabel42.setFont(new java.awt.Font("Chiller", 3, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 51));
        jLabel42.setText("ITEM NAME");
        getContentPane().add(jLabel42);
        jLabel42.setBounds(780, 400, 90, 20);

        jLabel43.setBackground(new java.awt.Color(255, 204, 204));
        jLabel43.setFont(new java.awt.Font("Chiller", 3, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 51));
        jLabel43.setText("ADD ");
        getContentPane().add(jLabel43);
        jLabel43.setBounds(630, 390, 40, 22);

        jLabel44.setBackground(new java.awt.Color(255, 204, 204));
        jLabel44.setFont(new java.awt.Font("Chiller", 3, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 51));
        jLabel44.setText("ITEM ");
        getContentPane().add(jLabel44);
        jLabel44.setBounds(620, 410, 50, 20);

        jLabel45.setBackground(new java.awt.Color(255, 204, 204));
        jLabel45.setFont(new java.awt.Font("Chiller", 3, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 51));
        jLabel45.setText("ITEM");
        getContentPane().add(jLabel45);
        jLabel45.setBounds(690, 410, 50, 20);

        jLabel46.setBackground(new java.awt.Color(255, 204, 204));
        jLabel46.setFont(new java.awt.Font("Chiller", 3, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 51));
        jLabel46.setText("REMOVE ");
        getContentPane().add(jLabel46);
        jLabel46.setBounds(690, 390, 70, 22);

        jLabel47.setBackground(new java.awt.Color(255, 204, 204));
        jLabel47.setFont(new java.awt.Font("Chiller", 3, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 51));
        jLabel47.setText("ADD ");
        getContentPane().add(jLabel47);
        jLabel47.setBounds(1010, 390, 40, 22);

        jLabel48.setBackground(new java.awt.Color(255, 204, 204));
        jLabel48.setFont(new java.awt.Font("Chiller", 3, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 51));
        jLabel48.setText("ITEM ");
        getContentPane().add(jLabel48);
        jLabel48.setBounds(1000, 410, 50, 20);

        jLabel49.setBackground(new java.awt.Color(255, 204, 204));
        jLabel49.setFont(new java.awt.Font("Chiller", 3, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 51));
        jLabel49.setText("ITEM");
        getContentPane().add(jLabel49);
        jLabel49.setBounds(1070, 410, 50, 20);

        jLabel50.setBackground(new java.awt.Color(255, 204, 204));
        jLabel50.setFont(new java.awt.Font("Chiller", 3, 18)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 51));
        jLabel50.setText("REMOVE ");
        getContentPane().add(jLabel50);
        jLabel50.setBounds(1070, 390, 70, 22);

        jLabel51.setBackground(new java.awt.Color(255, 204, 204));
        jLabel51.setFont(new java.awt.Font("Chiller", 3, 18)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 51));
        jLabel51.setText("ITEM NAME");
        getContentPane().add(jLabel51);
        jLabel51.setBounds(400, 400, 90, 20);

        jLabel41.setBackground(new java.awt.Color(255, 204, 204));
        jLabel41.setFont(new java.awt.Font("Chiller", 3, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 51));
        jLabel41.setText("QTY.");
        getContentPane().add(jLabel41);
        jLabel41.setBounds(560, 400, 40, 20);

        jLabel37.setFont(new java.awt.Font("Gungsuh", 3, 11)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 51));
        jLabel37.setText("DEIVERY MODE");
        getContentPane().add(jLabel37);
        jLabel37.setBounds(10, 270, 120, 30);

        fast.setBackground(new java.awt.Color(51, 255, 204));
        buttonGroup2.add(fast);
        fast.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fast.setForeground(new java.awt.Color(255, 204, 51));
        fast.setText("FAST DELIVERY");
        fast.setToolTipText("<html><font color=\"RED\" face=\"JOKERMAN\">FAST DELIVERY <br><br>WITHIN 30 min</font></html>");
        fast.setOpaque(false);
        getContentPane().add(fast);
        fast.setBounds(150, 300, 150, 25);

        normal.setBackground(new java.awt.Color(51, 255, 204));
        buttonGroup2.add(normal);
        normal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        normal.setForeground(new java.awt.Color(255, 204, 51));
        normal.setText("NORMAL DELIVERY");
        normal.setToolTipText("<html><font color=\"RED\" face=\"JOKERMAN\">NORMAL DELIVERY <br><br>WITHIN 1 TO 1.30 HR</font></html>");
        normal.setOpaque(false);
        getContentPane().add(normal);
        normal.setBounds(150, 270, 160, 25);

        jLabel38.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 204, 51));
        jLabel38.setText("CHARGE : 95 \\-");
        getContentPane().add(jLabel38);
        jLabel38.setBounds(310, 300, 130, 20);

        jLabel39.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 204, 51));
        jLabel39.setText("CHARGE : 55 \\-");
        getContentPane().add(jLabel39);
        jLabel39.setBounds(310, 270, 130, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hbackground.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1150, 730);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
int f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12,f13,f14,f15;
int t1,t2,t3,t4,t5,t6,t7,t8,t9,t10,t11,t12,t13,t14,t15;
    private void jButton70ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton70ActionPerformed
        // TODO add your handling code here:
        try{
            rs = stmt.executeQuery("select * from menu where itemcode= 1;");
            f1=Integer.parseInt(q1.getText());
            while(rs.next()){
                icode = rs.getInt("itemcode");
                p = rs.getInt("price");
                fdname = rs.getString("itemname");
                t = rs.getString("type");
                t1=f1*p;
            }
            rs.close();
            stmt.close();
            con.close();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill1 values("+icode+", '"+ t +"' , '"+ fdname+"','"+ t1 + "')");
        JOptionPane.showMessageDialog(null,"Added Succesfully");
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_jButton70ActionPerformed

    private void jButton71ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton71ActionPerformed
        // TODO add your handling code here:
        try{
            rs = stmt.executeQuery("select * from menu where itemcode= 2;");
            f2=Integer.parseInt(q2.getText());
            while(rs.next()){
                icode = rs.getInt("itemcode");
                p = rs.getInt("price");
                fdname = rs.getString("itemname");
                t = rs.getString("type");
                t2=f2*p;
            }
            rs.close();
            stmt.close();
            con.close();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill1 values("+icode+", '"+ t +"' , '"+ fdname+"','"+ t2 + "')");
        JOptionPane.showMessageDialog(null,"Added Succesfully");
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_jButton71ActionPerformed

    private void jButton72ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton72ActionPerformed
        // TODO add your handling code here:
        try{
            rs = stmt.executeQuery("select * from menu where itemcode= 3;");
            f3=Integer.parseInt(q3.getText());
            while(rs.next()){
                icode = rs.getInt("itemcode");
                p = rs.getInt("price");
                fdname = rs.getString("itemname");
                t = rs.getString("type");
                t3=f3*p;
            }
            rs.close();
            stmt.close();
            con.close();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill1 values("+icode+", '"+ t +"' , '"+ fdname+"','"+ t3 + "')");
        JOptionPane.showMessageDialog(null,"Added Succesfully");
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_jButton72ActionPerformed

    private void jButton73ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton73ActionPerformed
        // TODO add your handling code here:
        try{
            rs = stmt.executeQuery("select * from menu where itemcode= 4;");
            f4=Integer.parseInt(q4.getText());
            while(rs.next()){
                icode = rs.getInt("itemcode");
                p = rs.getInt("price");
                fdname = rs.getString("itemname");
                t = rs.getString("type");
                t4=f4*p;
            }
            rs.close();
            stmt.close();
            con.close();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill1 values("+icode+", '"+ t +"' , '"+ fdname+"','"+ t4 + "')");
        JOptionPane.showMessageDialog(null,"Added Succesfully");
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_jButton73ActionPerformed

    private void jButton74ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton74ActionPerformed
        // TODO add your handling code here:
        try{
            rs = stmt.executeQuery("select * from menu where itemcode= 5;");
            f5=Integer.parseInt(q5.getText());
            while(rs.next()){
                icode = rs.getInt("itemcode");
                p = rs.getInt("price");
                fdname = rs.getString("itemname");
                t = rs.getString("type");
                t5=f5*p;
            }
            rs.close();
            stmt.close();
            con.close();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill1 values("+icode+", '"+ t +"' , '"+ fdname+"','"+ t5 + "')");
        JOptionPane.showMessageDialog(null,"Added Succesfully");
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_jButton74ActionPerformed

    private void jButton75ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton75ActionPerformed
        // TODO add your handling code here:
        try{
            rs = stmt.executeQuery("select * from menu where itemcode= 6;");
            f6=Integer.parseInt(q6.getText());
            while(rs.next()){
                icode = rs.getInt("itemcode");
                p = rs.getInt("price");
                fdname = rs.getString("itemname");
                t = rs.getString("type");
                t6=f6*p;
            }
            rs.close();
            stmt.close();
            con.close();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill1 values("+icode+", '"+ t +"' , '"+ fdname+"','"+ t6 + "')");
        JOptionPane.showMessageDialog(null,"Added Succesfully");
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_jButton75ActionPerformed

    private void jButton76ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton76ActionPerformed
        // TODO add your handling code here:
        try{
            rs = stmt.executeQuery("select * from menu where itemcode= 7;");
            f7=Integer.parseInt(q7.getText());
            while(rs.next()){
                icode = rs.getInt("itemcode");
                p = rs.getInt("price");
                fdname = rs.getString("itemname");
                t = rs.getString("type");
                t7=f7*p;
            }
            rs.close();
            stmt.close();
            con.close();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill1 values("+icode+", '"+ t +"' , '"+ fdname+"','"+ t7 + "')");
        JOptionPane.showMessageDialog(null,"Added Succesfully");
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_jButton76ActionPerformed

    private void jButton77ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton77ActionPerformed
        // TODO add your handling code here:
        try{
            rs = stmt.executeQuery("select * from menu where itemcode= 8;");
            f8=Integer.parseInt(q8.getText());
            while(rs.next()){
                icode = rs.getInt("itemcode");
                p = rs.getInt("price");
                fdname = rs.getString("itemname");
                t = rs.getString("type");
                t8=f8*p;
            }
            rs.close();
            stmt.close();
            con.close();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill1 values("+icode+", '"+ t +"' , '"+ fdname+"','"+ t8 + "')");
        JOptionPane.showMessageDialog(null,"Added Succesfully");
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_jButton77ActionPerformed

    private void jButton78ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton78ActionPerformed
        // TODO add your handling code here:
        try{
            rs = stmt.executeQuery("select * from menu where itemcode= 9;");

            f9=Integer.parseInt(q9.getText());
            while(rs.next()){
                icode = rs.getInt("itemcode");
                p = rs.getInt("price");
                fdname = rs.getString("itemname");
                t = rs.getString("type");
                t9=f9*p;
            }
            rs.close();
            stmt.close();
            con.close();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill1 values("+icode+", '"+ t +"' , '"+ fdname+"','"+ t9 + "')");
        JOptionPane.showMessageDialog(null,"Added Succesfully");
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_jButton78ActionPerformed

    private void jButton79ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton79ActionPerformed
        // TODO add your handling code here:
        try{
            rs = stmt.executeQuery("select * from menu where itemcode= 10;");
            f10=Integer.parseInt(q10.getText());
            while(rs.next()){
                icode = rs.getInt("itemcode");
                p = rs.getInt("price");
                fdname = rs.getString("itemname");
                t = rs.getString("type");
                t10=f10*p;
            }
            rs.close();
            stmt.close();
            con.close();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill1 values("+icode+", '"+ t +"' , '"+ fdname+"','"+ t10 + "')");
        JOptionPane.showMessageDialog(null,"Added Succesfully");
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_jButton79ActionPerformed

    private void jButton80ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton80ActionPerformed
        // TODO add your handling code here:
        try{
            rs = stmt.executeQuery("select * from menu where itemcode= 11;");
            f11=Integer.parseInt(q11.getText());
            while(rs.next()){
                icode = rs.getInt("itemcode");
                p = rs.getInt("price");
                fdname = rs.getString("itemname");
                t = rs.getString("type");
                t11=f11*p;
            }
            rs.close();
            stmt.close();
            con.close();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill1 values("+icode+", '"+ t +"' , '"+ fdname+"','"+ t11 + "')");
        JOptionPane.showMessageDialog(null,"Added Succesfully");
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_jButton80ActionPerformed

    private void jButton81ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton81ActionPerformed
        // TODO add your handling code here:
        try{
            rs = stmt.executeQuery("select * from menu where itemcode= 12;");
            f12=Integer.parseInt(q12.getText());
            while(rs.next()){
                icode = rs.getInt("itemcode");
                p = rs.getInt("price");
                fdname = rs.getString("itemname");
                t = rs.getString("type");
                t12=f12*p;
            }
            rs.close();
            stmt.close();
            con.close();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill1 values("+icode+", '"+ t +"' , '"+ fdname+"','"+ t12 + "')");
        JOptionPane.showMessageDialog(null,"Added Succesfully");
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_jButton81ActionPerformed

    private void jButton82ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton82ActionPerformed
        // TODO add your handling code here:
        try{
            rs = stmt.executeQuery("select * from menu where itemcode= 13;");
            f13=Integer.parseInt(q13.getText());
            while(rs.next()){
                icode = rs.getInt("itemcode");
                p = rs.getInt("price");
                fdname = rs.getString("itemname");
                t = rs.getString("type");
                t13=f13*p;
            }
            rs.close();
            stmt.close();
            con.close();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill1 values("+icode+", '"+ t +"' , '"+ fdname+"','"+ t13 + "')");
        JOptionPane.showMessageDialog(null,"Added Succesfully");
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_jButton82ActionPerformed

    private void jButton83ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton83ActionPerformed
        // TODO add your handling code here:
        try{
            rs = stmt.executeQuery("select * from menu where itemcode= 14;");
            f14=Integer.parseInt(q14.getText());
            while(rs.next()){
                icode = rs.getInt("itemcode");
                p = rs.getInt("price");
                fdname = rs.getString("itemname");
                t = rs.getString("type");
                t14=f14*p;
            }
            rs.close();
            stmt.close();
            con.close();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill1 values("+icode+", '"+ t +"' , '"+ fdname+"','"+ t14 + "')");
        JOptionPane.showMessageDialog(null,"Added Succesfully");
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_jButton83ActionPerformed

    private void jButton84ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton84ActionPerformed
        // TODO add your handling code here:
        try{
            rs = stmt.executeQuery("select * from menu where itemcode= 15;");
            f15=Integer.parseInt(q15.getText());
            while(rs.next()){
                icode = rs.getInt("itemcode");
                p = rs.getInt("price");
                fdname = rs.getString("itemname");
                t = rs.getString("type");
                t15=f15*p;
            }
            rs.close();
            stmt.close();
            con.close();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill1 values("+icode+", '"+ t +"' , '"+ fdname+"','"+ t15 + "')");
        JOptionPane.showMessageDialog(null,"Added Succesfully");
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_jButton84ActionPerformed

    private void q1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_q1ActionPerformed

    private void q3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_q3ActionPerformed

    private void q6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q6ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_q6ActionPerformed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_dateActionPerformed

    private void monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_monthActionPerformed

    private void nocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nocActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_nocActionPerformed

    private void phnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phnActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_phnActionPerformed

    private void nopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nopActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_nopActionPerformed
String mp;
String md;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         ImageIcon ic;
        ic = new ImageIcon("C:/Users/yj/Desktop/Class_IP_Project/src/Screenshot_20171115-213311.png");
        if(phn.getText().length()>10||phn.getText().length()<10){
            JOptionPane.showMessageDialog(null,"ENTER VAID PHONE NUMBER X(");
        } else{
            try{
                Class.forName("java.sql.Driver");
                con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","");
                String orno=on.getText();
                String d = (String) date.getSelectedItem();
                String m = (String) month.getSelectedItem();
                String y = (String) year.getSelectedItem();
                String dt=y+"-"+m+"-"+d;                        //Date
                String nc=noc.getText();                        //Name Of Customer
                String pn=phn.getText();                        //Phone Number
                String np= (String) nop.getSelectedItem();      //No. Of People
                String add=address.getText();                   //Address
                String ct = (String) city.getSelectedItem();     //city
                String lmark=landmark.getText();                //landmark
                String pin=pincode.getText();                   //pincode
                if(ca.isSelected()==true){
                    mp = "Cash";
                } else
                    if(cc.isSelected()==true){                   //mode of payment
                        mp = "Credit Crard";
                    } else
                        if(dc.isSelected()==true){
                            mp = "Debit Card";
                        }

                if(normal.isSelected()==true){
                    md = "NORMAL DELIVERY";
                } else
                    if(fast.isSelected()==true){             //mode of DELIVERY
                        md = "FAST DELIVERY";
                    }
                String query= "insert into orders1 values("+orno + ", '"+ dt + "' , '" + nc + "' , '"+ pn
                        +"' , '"+add+"' , '"+ct+"' , '"+pin+"' , '"+lmark+"' ,'"+md+"' , '"+ np +"' , '"+ mp +" ' "+");";
                stmt=con.createStatement();
                int res=stmt.executeUpdate(query);
                JOptionPane.showMessageDialog(null,"","THANK YOU SIR :)",JOptionPane.PLAIN_MESSAGE,ic);
                Billing_Form1 bf1 = new Billing_Form1();
                bf1.setVisible(true);
                this.setVisible(false);
            } catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }}
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Welcome_Screen_ ws=new Welcome_Screen_();
        ws.setVisible(true);
        this.setVisible(false);
}//GEN-LAST:event_jButton6ActionPerformed

    private void jButton69ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton69ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill1 where sno = 15;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(null,"Removed Succesfully");
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_jButton69ActionPerformed

    private void jButton85ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton85ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill1 where sno = 14;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(null,"Removed Succesfully");
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_jButton85ActionPerformed

    private void jButton86ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton86ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill1 where sno = 1;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(null,"Removed Succesfully");
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_jButton86ActionPerformed

    private void jButton87ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton87ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill1 where sno = 2;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(null,"Removed Succesfully");
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_jButton87ActionPerformed

    private void jButton88ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton88ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill1 where sno = 3;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(null,"Removed Succesfully");
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_jButton88ActionPerformed

    private void jButton89ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton89ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill1 where sno = 4;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(null,"Removed Succesfully");
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_jButton89ActionPerformed

    private void jButton90ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton90ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill1 where sno = 5;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(null,"Removed Succesfully");
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_jButton90ActionPerformed

    private void jButton91ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton91ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill1 where sno = 6;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(null,"Removed Succesfully");
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_jButton91ActionPerformed

    private void jButton92ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton92ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill1 where sno = 7;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(null,"Removed Succesfully");
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_jButton92ActionPerformed

    private void jButton93ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton93ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill1 where sno = 8;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(null,"Removed Succesfully");
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_jButton93ActionPerformed

    private void jButton94ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton94ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill1 where sno = 9;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(null,"Removed Succesfully");
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_jButton94ActionPerformed

    private void jButton95ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton95ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill1 where sno = 10;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(null,"Removed Succesfully");
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_jButton95ActionPerformed

    private void jButton96ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton96ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill1 where sno = 11;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(null,"Removed Succesfully");
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_jButton96ActionPerformed

    private void jButton97ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton97ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill1 where sno = 12;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(null,"Removed Succesfully");
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_jButton97ActionPerformed

    private void jButton98ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton98ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("Delete from bill1 where sno = 13;");
        rs.close();
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(null,"Removed Succesfully");
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_jButton98ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        q1.setText("");
        q2.setText("");
        q3.setText("");
        q4.setText("");
        q5.setText("");
        q6.setText("");
        q7.setText("");
        q8.setText("");
        q9.setText("");
        q10.setText("");
        q11.setText("");
        q12.setText("");
        q13.setText("");
        q14.setText("");
        q15.setText("");
        on.setText("");
        noc.setText("");
        phn.setText("");
        ca.setSelected(false);
        cc.setSelected(false);
        dc.setSelected(false);
        date.setSelectedIndex(0);
        month.setSelectedIndex(0);
        year.setSelectedIndex(0);
}//GEN-LAST:event_jButton1ActionPerformed

    private void onActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_onActionPerformed

    private void dcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dcActionPerformed

    private void onKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_onKeyTyped
        // TODO add your handling code here:
         if(on.getText().equals("")){
            on.setBackground(Color.WHITE);
        }else
        {
           on.setBackground(Color.YELLOW); 
        }
    }//GEN-LAST:event_onKeyTyped

    private void nocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nocKeyTyped
        // TODO add your handling code here:
         if(noc.getText().equals("")){
            noc.setBackground(Color.WHITE);
        }else
        {
           noc.setBackground(Color.YELLOW); 
        }
    }//GEN-LAST:event_nocKeyTyped

    private void phnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phnKeyTyped
        // TODO add your handling code here:
         if(phn.getText().equals("")){
            phn.setBackground(Color.WHITE);
        }else
        {
           phn.setBackground(Color.YELLOW); 
        }
    }//GEN-LAST:event_phnKeyTyped

    private void addressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressKeyTyped
        // TODO add your handling code here:
         if(address.getText().equals("")){
            address.setBackground(Color.WHITE);
        }else
        {
           address.setBackground(Color.YELLOW); 
        }
    }//GEN-LAST:event_addressKeyTyped

    private void pincodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pincodeKeyTyped
        // TODO add your handling code here:
         if(pincode.getText().equals("")){
            pincode.setBackground(Color.WHITE);
        }else
        {
           pincode.setBackground(Color.YELLOW); 
        }
    }//GEN-LAST:event_pincodeKeyTyped

    private void landmarkKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_landmarkKeyTyped
        // TODO add your handling code here:
         if(landmark.getText().equals("")){
            landmark.setBackground(Color.WHITE);
        }else
        {
           landmark.setBackground(Color.YELLOW); 
        }
    }//GEN-LAST:event_landmarkKeyTyped

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_Delivery().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea address;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton ca;
    private javax.swing.JRadioButton cc;
    private javax.swing.JComboBox city;
    private javax.swing.JComboBox date;
    private javax.swing.JRadioButton dc;
    private javax.swing.JRadioButton fast;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton70;
    private javax.swing.JButton jButton71;
    private javax.swing.JButton jButton72;
    private javax.swing.JButton jButton73;
    private javax.swing.JButton jButton74;
    private javax.swing.JButton jButton75;
    private javax.swing.JButton jButton76;
    private javax.swing.JButton jButton77;
    private javax.swing.JButton jButton78;
    private javax.swing.JButton jButton79;
    private javax.swing.JButton jButton80;
    private javax.swing.JButton jButton81;
    private javax.swing.JButton jButton82;
    private javax.swing.JButton jButton83;
    private javax.swing.JButton jButton84;
    private javax.swing.JButton jButton85;
    private javax.swing.JButton jButton86;
    private javax.swing.JButton jButton87;
    private javax.swing.JButton jButton88;
    private javax.swing.JButton jButton89;
    private javax.swing.JButton jButton90;
    private javax.swing.JButton jButton91;
    private javax.swing.JButton jButton92;
    private javax.swing.JButton jButton93;
    private javax.swing.JButton jButton94;
    private javax.swing.JButton jButton95;
    private javax.swing.JButton jButton96;
    private javax.swing.JButton jButton97;
    private javax.swing.JButton jButton98;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField landmark;
    private javax.swing.JComboBox month;
    private javax.swing.JTextField noc;
    private javax.swing.JComboBox nop;
    private javax.swing.JRadioButton normal;
    private javax.swing.JTextField on;
    private javax.swing.JTextField phn;
    private javax.swing.JTextField pincode;
    private javax.swing.JTextField q1;
    private javax.swing.JTextField q10;
    private javax.swing.JTextField q11;
    private javax.swing.JTextField q12;
    private javax.swing.JTextField q13;
    private javax.swing.JTextField q14;
    private javax.swing.JTextField q15;
    private javax.swing.JTextField q2;
    private javax.swing.JTextField q3;
    private javax.swing.JTextField q4;
    private javax.swing.JTextField q5;
    private javax.swing.JTextField q6;
    private javax.swing.JTextField q7;
    private javax.swing.JTextField q8;
    private javax.swing.JTextField q9;
    private javax.swing.JComboBox year;
    // End of variables declaration//GEN-END:variables

}
