import java.sql.*;
import javax.swing.JOptionPane;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Info_Update.java
 *
 * Created on Nov 18, 2017, 9:45:05 PM
 */

/**
 *
 * @author Yuvansh
 */
public class Info_Update extends javax.swing.JFrame {
     Connection con = null;
Statement stmt = null;


    /** Creates new form Info_Update */
    public Info_Update() {
        initComponents();
        try{
            Class.forName("com.mysql.jdbc.Driver");
          con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","");
        stmt= con.createStatement();
         ResultSet rs = stmt.executeQuery("select username,password from username u ,signup s where u.uname=s.username;");
          while(rs.next()){
        String u = rs.getString("username");
        String p = rs.getString("password");
        adr.setText(""+u);
        password.setText(""+p);
        }
         }
        catch(Exception e)
                 {
            JOptionPane.showMessageDialog(null,e);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        phno = new javax.swing.JTextField();
        cpwd = new javax.swing.JTextField();
        fnm = new javax.swing.JTextField();
        lnm = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        adr = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1015, 660));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel1.setText("PHONE NUMBER");
        jLabel1.setEnabled(false);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 400, 150, 30);

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel3.setText("CONFIRM PASSSWORD");
        jLabel3.setEnabled(false);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 350, 190, 30);

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel4.setText("FIRST NAME");
        jLabel4.setEnabled(false);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 250, 150, 30);

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel5.setText("LAST NAME");
        jLabel5.setEnabled(false);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 300, 150, 30);

        search.setFont(new java.awt.Font("Baskerville Old Face", 3, 24)); // NOI18N
        search.setText("SEARCH");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search);
        search.setBounds(20, 480, 140, 40);

        update.setFont(new java.awt.Font("Baskerville Old Face", 3, 24)); // NOI18N
        update.setText("UPDATE");
        update.setEnabled(false);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(170, 480, 150, 40);

        delete.setFont(new java.awt.Font("Baskerville Old Face", 3, 24)); // NOI18N
        delete.setText("DELETE");
        delete.setEnabled(false);
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete);
        delete.setBounds(330, 480, 150, 40);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon.png"))); // NOI18N
        jButton6.setToolTipText("<html><font color=\"RED\" face=\"JOKERMAN\">HOME</font></html>");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(200, 20, 50, 50);

        jLabel8.setBackground(new java.awt.Color(204, 204, 255));
        jLabel8.setForeground(new java.awt.Color(255, 255, 204));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/471074.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 20, 200, 90);

        phno.setEnabled(false);
        getContentPane().add(phno);
        phno.setBounds(300, 400, 290, 30);

        cpwd.setEnabled(false);
        getContentPane().add(cpwd);
        cpwd.setBounds(300, 350, 290, 30);

        fnm.setEnabled(false);
        getContentPane().add(fnm);
        fnm.setBounds(300, 250, 290, 30);

        lnm.setEnabled(false);
        getContentPane().add(lnm);
        lnm.setBounds(300, 300, 290, 30);

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel6.setText("PASSSWORD");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 200, 150, 30);
        getContentPane().add(password);
        password.setBounds(300, 200, 290, 30);

        jLabel9.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel9.setText("USERNAME");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(60, 150, 150, 30);
        getContentPane().add(adr);
        adr.setBounds(300, 150, 290, 30);

        jLabel2.setFont(new java.awt.Font("Castellar", 2, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 255));
        jLabel2.setText("INFORMATION UPDATE ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(310, 10, 660, 80);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abstract-wallpapers-hd-3d-hole.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 1000, 624);

        setSize(new java.awt.Dimension(1016, 667));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Welcome_Screen_ ws=new Welcome_Screen_();
        ws.setVisible(true);
        this.setVisible(false);
}//GEN-LAST:event_jButton6ActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:       
          try{
            Class.forName("com.mysql.jdbc.Driver");
         con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","");
        stmt= con.createStatement();
        ResultSet rs = stmt.executeQuery("select * from signup where username='"+adr.getText()+"';");
          while(rs.next()){
        String u = rs.getString("USERNAME");
        String fn = rs.getString("FNAME");
        String ln = rs.getString("LNAME");
        String pass = rs.getString("PASSWORD");
        String cpass = rs.getString("CONFIRMPASS");
        String ph = rs.getString("PHN_NUMBER");
        fnm.setText(""+fn);
        lnm.setText(""+ln);
        password.setText(""+pass);
        cpwd.setText(""+cpass);
        phno.setText(""+ph);
        }
           fnm.setEnabled(true);
        lnm.setEnabled(true);
        cpwd.setEnabled(true);
        phno.setEnabled(true);
        jLabel1.setEnabled(true);
        jLabel3.setEnabled(true);
        jLabel4.setEnabled(true);
        jLabel5.setEnabled(true);
        delete.setEnabled(true);
        update.setEnabled(true);}
        catch(Exception e)
                 {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_searchActionPerformed
//String u,fn,ln,pass,cpass,ph;
    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
       if(password.getText().equals(cpwd.getText())){
         try{
            Class.forName("com.mysql.jdbc.Driver");
         con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","");
        stmt= con.createStatement();
       String u =adr.getText();
       String pass =password.getText();
       String cpass =cpwd.getText();
       String fn =fnm.getText();
       String ln =lnm.getText();
        String ph =phno.getText();
       int res = stmt.executeUpdate("update signup set fname='"+fn+"' , lname='"+ln+"', password='"+pass+"' , confirmpass='"+cpass
                                                  +"' , username='"+u+"' , phn_Number='"+ph+"';");
  

         JOptionPane.showMessageDialog(null,"!!! RECORD UPDATED SUCESSFUY !!!");

         }

        catch(Exception e)
                 {
            JOptionPane.showMessageDialog(null,e);
        }} else {
            JOptionPane.showMessageDialog(null,"!!! INVALID PASSWORD ENTRY !!!");
        }
}//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
         try{
            Class.forName("com.mysql.jdbc.Driver");
         con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","");
        stmt= con.createStatement();

       int res = stmt.executeUpdate("delete from signup WHERE username='"+adr.getText()+"';");
      JOptionPane.showMessageDialog(null,"!!! RECORD DELETED SUCESSFUY !!!");
       Login_Form lf=new Login_Form();
        lf.setVisible(true);
        this.setVisible(false);
         }

        catch(Exception e)
                 {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_deleteActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Info_Update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adr;
    private javax.swing.JTextField cpwd;
    private javax.swing.JButton delete;
    private javax.swing.JTextField fnm;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lnm;
    private javax.swing.JTextField password;
    private javax.swing.JTextField phno;
    private javax.swing.JButton search;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

}
