import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Menu_Card.java
 *
 * Created on Oct 23, 2017, 12:57:42 PM
 */

/**
 *
 * @author Yuvansh
 */
public class Menu_Card extends javax.swing.JFrame {
    Connection con = null;
Statement stmt = null;
ResultSet rs = null;



    /** Creates new form Menu_Card */
    public Menu_Card() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        typ = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        nm = new javax.swing.JTextField();
        nprc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        pss = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(980, 500));
        getContentPane().setLayout(null);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search-icon_1598775.jpg"))); // NOI18N
        jButton2.setToolTipText("<html><font color=\"RED\" face=\"JOKERMAN\">SEARCH</font></html>");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(660, 110, 70, 60);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modify-button-blue-hi.png"))); // NOI18N
        jButton4.setToolTipText("<html><font color=\"RED\" face=\"JOKERMAN\">MODIFY</font></html>");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(40, 330, 120, 40);

        tb.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ITEM CODE", "TYPE", "ITEM NAME", "PRICE"
            }
        ));
        tb.setEnabled(false);
        tb.setOpaque(false);
        jScrollPane1.setViewportView(tb);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(380, 180, 600, 280);

        typ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                typMouseClicked(evt);
            }
        });
        typ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typActionPerformed(evt);
            }
        });
        getContentPane().add(typ);
        typ.setBounds(380, 130, 250, 30);

        jLabel1.setText("Enter Item Name");
        jLabel1.setEnabled(false);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 240, 120, 30);

        nm.setEnabled(false);
        nm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmActionPerformed(evt);
            }
        });
        getContentPane().add(nm);
        nm.setBounds(190, 240, 160, 30);

        nprc.setEnabled(false);
        nprc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nprcActionPerformed(evt);
            }
        });
        getContentPane().add(nprc);
        nprc.setBounds(190, 290, 160, 30);

        jLabel4.setBackground(new java.awt.Color(153, 153, 255));
        jLabel4.setFont(new java.awt.Font("Bell MT", 3, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("MENU CARD ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(350, 20, 340, 50);

        jLabel2.setText("Enter Item new price");
        jLabel2.setEnabled(false);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 290, 120, 30);

        jLabel5.setBackground(new java.awt.Color(204, 204, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/471074.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 20, 200, 92);

        jLabel6.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel6.setText("ENTER ITEM TYPE TO SEARCH");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(380, 90, 210, 30);

        jButton3.setForeground(new java.awt.Color(102, 102, 255));
        jButton3.setText("CICK HERE");
        jButton3.setOpaque(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(210, 150, 120, 23);

        jLabel7.setText("FOR UPDATION --->");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 110, 120, 40);

        jButton5.setForeground(new java.awt.Color(102, 102, 255));
        jButton5.setText("CLEAR");
        jButton5.setToolTipText("<html><font color=\"RED\" face=\"JOKERMAN\">CLEAR</font></html>");
        jButton5.setOpaque(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(750, 110, 80, 60);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("*only for owner");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 150, 110, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("*Enter owner Password");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 170, 160, 30);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon.png"))); // NOI18N
        jButton6.setToolTipText("<html><font color=\"RED\" face=\"JOKERMAN\">HOME</font></html>");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(220, 20, 50, 50);
        getContentPane().add(pss);
        pss.setBounds(210, 120, 120, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1000, 480);

        setSize(new java.awt.Dimension(1018, 521));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       try{
            Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","");
        stmt= con.createStatement();
        String query="select * from menu where type = '"+typ.getText()+"';";
        rs=stmt.executeQuery(query);
       DefaultTableModel tbl = (DefaultTableModel) tb.getModel();
      tb.setSelectionBackground(Color.ORANGE);
       while (rs.next()) {
    String  ic = rs.getString("Itemcode");
    String  ty = rs.getString("Type");
    String  in = rs.getString("ItemName");
    String  prc = rs.getString("Price");
    Object[] row={ic, ty, in, prc};
    tbl.addRow(row);  
       }
    
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","");
        stmt= con.createStatement();
        String query="Update menu Set Price = "+nprc.getText()+" where ItemName ='"+nm.getText()+"';";
       int res=stmt.executeUpdate(query);
       JOptionPane.showMessageDialog(null,"!!! YOUR ITEM UPDATED SUCESSFULLY !!!");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void nmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_nmActionPerformed

    private void nprcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nprcActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_nprcActionPerformed

    private void typActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_typActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         String pwd1 =new String(pss.getPassword());
       if(pwd1.equals("gym")){
            JOptionPane.showMessageDialog(null,"WELCOME SIR , NOW YOU ARE AUTHORISE TO UPDATE ITEM PRICE");
        jLabel1.setEnabled(true);
        jLabel2.setEnabled(true);
        nm.setEnabled(true);      
        nprc.setEnabled(true);
        jButton4.setEnabled(true);
         pss.setText("");
        } 
            else {

        jLabel1.setEnabled(false);
        jLabel2.setEnabled(false);
        nm.setEnabled(false);
        nprc.setEnabled(false);
        jButton4.setEnabled(false);
        pss.setText("");
           JOptionPane.showMessageDialog(null,"        !!! PASSWORD ENTERED IS WRONG !!!"+
                                              "\n \n !!! PLEASE ENTER CORRECT OWNER PASSWORD !!!");
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        ((DefaultTableModel)tb.getModel()).setNumRows(0);
        typ.setText("");
        nm.setText("");
        nprc.setText("");

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Welcome_Screen_ ws=new Welcome_Screen_();
        ws.setVisible(true);
        this.setVisible(false);
}//GEN-LAST:event_jButton6ActionPerformed

    private void typMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_typMouseClicked
        // TODO add your handling code here:
        typ.setText("");
    }//GEN-LAST:event_typMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Card().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nm;
    private javax.swing.JTextField nprc;
    private javax.swing.JPasswordField pss;
    private javax.swing.JTable tb;
    private javax.swing.JTextField typ;
    // End of variables declaration//GEN-END:variables

}
