import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
/*
 * To change this template, choose Tools | Templates
import java.sql.*;
import javax.swing.JOptionPane;
 * and open the template in the editor.
 */

/*
 * pooo.java
 *
 * Created on Nov 7, 2017, 7:11:45 PM
 */

/**
 *
 * @author Yuvansh
 */
public class Placing_Order extends javax.swing.JFrame {
Connection con = null;
Statement stmt = null;
ResultSet rs= null;
int icode, p;
String fdname,t;

    /** Creates new form pooo */
    public Placing_Order() {
        initComponents();
         try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
        stmt= con.createStatement();

      //  rs.close();
       // stmt.close();
      //  con.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton70 = new javax.swing.JButton();
        jButton71 = new javax.swing.JButton();
        jButton72 = new javax.swing.JButton();
        jButton73 = new javax.swing.JButton();
        jButton74 = new javax.swing.JButton();
        jButton75 = new javax.swing.JButton();
        jButton76 = new javax.swing.JButton();
        jButton77 = new javax.swing.JButton();
        jButton78 = new javax.swing.JButton();
        jButton79 = new javax.swing.JButton();
        jButton80 = new javax.swing.JButton();
        jButton81 = new javax.swing.JButton();
        jButton82 = new javax.swing.JButton();
        jButton83 = new javax.swing.JButton();
        jButton84 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        q1 = new javax.swing.JTextField();
        q2 = new javax.swing.JTextField();
        q3 = new javax.swing.JTextField();
        q4 = new javax.swing.JTextField();
        q5 = new javax.swing.JTextField();
        q6 = new javax.swing.JTextField();
        q7 = new javax.swing.JTextField();
        q8 = new javax.swing.JTextField();
        q9 = new javax.swing.JTextField();
        q10 = new javax.swing.JTextField();
        q15 = new javax.swing.JTextField();
        q14 = new javax.swing.JTextField();
        q13 = new javax.swing.JTextField();
        q12 = new javax.swing.JTextField();
        q11 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        date = new javax.swing.JComboBox();
        month = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        year = new javax.swing.JComboBox();
        jLabel26 = new javax.swing.JLabel();
        on = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        noc = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        phn = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        nop = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        ca = new javax.swing.JRadioButton();
        cc = new javax.swing.JRadioButton();
        dc = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton69 = new javax.swing.JButton();
        jButton85 = new javax.swing.JButton();
        jButton86 = new javax.swing.JButton();
        jButton87 = new javax.swing.JButton();
        jButton88 = new javax.swing.JButton();
        jButton89 = new javax.swing.JButton();
        jButton90 = new javax.swing.JButton();
        jButton91 = new javax.swing.JButton();
        jButton92 = new javax.swing.JButton();
        jButton93 = new javax.swing.JButton();
        jButton94 = new javax.swing.JButton();
        jButton95 = new javax.swing.JButton();
        jButton96 = new javax.swing.JButton();
        jButton97 = new javax.swing.JButton();
        jButton98 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1030, 590));
        getContentPane().setLayout(null);

        jButton70.setBackground(new java.awt.Color(204, 255, 204));
        jButton70.setText("Add");
        jButton70.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton70ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton70);
        jButton70.setBounds(270, 100, 60, 23);

        jButton71.setBackground(new java.awt.Color(204, 255, 204));
        jButton71.setText("Add");
        jButton71.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton71ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton71);
        jButton71.setBounds(270, 130, 60, 23);

        jButton72.setBackground(new java.awt.Color(204, 255, 204));
        jButton72.setText("Add ");
        jButton72.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton72ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton72);
        jButton72.setBounds(270, 160, 60, 23);

        jButton73.setBackground(new java.awt.Color(204, 255, 204));
        jButton73.setText("Add ");
        jButton73.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton73ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton73);
        jButton73.setBounds(270, 190, 60, 23);

        jButton74.setBackground(new java.awt.Color(204, 255, 204));
        jButton74.setText("Add ");
        jButton74.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton74ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton74);
        jButton74.setBounds(270, 220, 60, 23);

        jButton75.setBackground(new java.awt.Color(204, 255, 204));
        jButton75.setText("Add ");
        jButton75.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton75ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton75);
        jButton75.setBounds(270, 310, 60, 23);

        jButton76.setBackground(new java.awt.Color(204, 255, 204));
        jButton76.setText("Add ");
        jButton76.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton76ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton76);
        jButton76.setBounds(270, 340, 60, 23);

        jButton77.setBackground(new java.awt.Color(204, 255, 204));
        jButton77.setText("Add ");
        jButton77.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton77ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton77);
        jButton77.setBounds(270, 370, 60, 23);

        jButton78.setBackground(new java.awt.Color(204, 255, 204));
        jButton78.setText("Add ");
        jButton78.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton78ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton78);
        jButton78.setBounds(270, 400, 60, 23);

        jButton79.setBackground(new java.awt.Color(204, 255, 204));
        jButton79.setText("Add ");
        jButton79.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton79ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton79);
        jButton79.setBounds(270, 430, 60, 23);

        jButton80.setBackground(new java.awt.Color(204, 255, 204));
        jButton80.setText("Add ");
        jButton80.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton80ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton80);
        jButton80.setBounds(270, 520, 60, 23);

        jButton81.setBackground(new java.awt.Color(204, 255, 204));
        jButton81.setText("Add ");
        jButton81.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton81ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton81);
        jButton81.setBounds(270, 550, 60, 23);

        jButton82.setBackground(new java.awt.Color(204, 255, 204));
        jButton82.setText("Add ");
        jButton82.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton82ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton82);
        jButton82.setBounds(270, 580, 60, 23);

        jButton83.setBackground(new java.awt.Color(204, 255, 204));
        jButton83.setText("Add ");
        jButton83.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton83ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton83);
        jButton83.setBounds(270, 610, 60, 23);

        jButton84.setBackground(new java.awt.Color(204, 255, 204));
        jButton84.setText("Add ");
        jButton84.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton84ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton84);
        jButton84.setBounds(270, 640, 60, 23);

        jLabel20.setFont(new java.awt.Font("Chiller", 3, 48)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("STARTER");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(150, 50, 180, 40);

        jLabel21.setFont(new java.awt.Font("Chiller", 3, 48)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("JUICES");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(160, 260, 160, 40);

        jLabel22.setFont(new java.awt.Font("Chiller", 3, 48)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("BEVERAES");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(140, 470, 210, 40);

        jLabel1.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel1.setText("MEXICAN SIZZLER");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 130, 140, 20);

        jLabel2.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel2.setText("VEG. CHEESE BURGER");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 160, 160, 20);

        jLabel3.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel3.setText("FRENCH FRIES");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 190, 140, 20);

        jLabel4.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel4.setText("VEG SANDWHICH");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 220, 140, 20);

        jLabel5.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel5.setText("HOT COFFEE");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 520, 140, 20);

        jLabel6.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel6.setText("COLD COFFEE ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 550, 140, 20);

        jLabel7.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel7.setText("STRAWBERRY SHAKE");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 580, 140, 20);

        jLabel9.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel9.setText("MIX FRUIT SHAKE");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 610, 140, 20);

        jLabel10.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel10.setText("MANGO SHAKE");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 640, 140, 20);

        jLabel11.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel11.setText("DUTCHES OF WINDSTAR");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 320, 180, 20);

        jLabel12.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel12.setText("FLOSBERRY FLOB");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(10, 350, 140, 20);

        jLabel13.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel13.setText("SWEET LIME");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 380, 140, 20);

        jLabel14.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel14.setText("APPLE");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(10, 410, 140, 20);

        jLabel15.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel15.setText("PINEAPPLE");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(10, 440, 140, 20);

        jLabel16.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel16.setText("DRY MANCHURIAN");
        jLabel16.setToolTipText("<html><img src=\"C:\\Users\\Yuvansh\\Documents\\NetBeansProjects\\Class_IP_Project\\src\\1036_-_Cancel_Order-512.png\"></html>");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(10, 100, 140, 20);

        jLabel17.setBackground(new java.awt.Color(255, 204, 204));
        jLabel17.setFont(new java.awt.Font("Chiller", 3, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 255));
        jLabel17.setText("ITEM NAME");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(60, 10, 90, 20);

        jLabel18.setBackground(new java.awt.Color(255, 204, 204));
        jLabel18.setFont(new java.awt.Font("Chiller", 3, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 255));
        jLabel18.setText("REMOVE FROM");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(350, 10, 110, 22);

        jLabel19.setBackground(new java.awt.Color(255, 204, 204));
        jLabel19.setFont(new java.awt.Font("Chiller", 3, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 255));
        jLabel19.setText("QTY.");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(200, 10, 40, 20);

        q1.setBackground(new java.awt.Color(255, 204, 204));
        q1.setFont(new java.awt.Font("High Tower Text", 3, 18)); // NOI18N
        q1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1ActionPerformed(evt);
            }
        });
        getContentPane().add(q1);
        q1.setBounds(190, 100, 50, 28);

        q2.setBackground(new java.awt.Color(255, 204, 204));
        q2.setFont(new java.awt.Font("High Tower Text", 3, 18)); // NOI18N
        getContentPane().add(q2);
        q2.setBounds(190, 130, 50, 28);

        q3.setBackground(new java.awt.Color(255, 204, 204));
        q3.setFont(new java.awt.Font("High Tower Text", 3, 18)); // NOI18N
        q3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3ActionPerformed(evt);
            }
        });
        getContentPane().add(q3);
        q3.setBounds(190, 160, 50, 28);

        q4.setBackground(new java.awt.Color(255, 204, 204));
        q4.setFont(new java.awt.Font("High Tower Text", 3, 18)); // NOI18N
        getContentPane().add(q4);
        q4.setBounds(190, 190, 50, 28);

        q5.setBackground(new java.awt.Color(255, 204, 204));
        q5.setFont(new java.awt.Font("High Tower Text", 3, 18)); // NOI18N
        getContentPane().add(q5);
        q5.setBounds(190, 220, 50, 28);

        q6.setBackground(new java.awt.Color(255, 204, 204));
        q6.setFont(new java.awt.Font("High Tower Text", 3, 18)); // NOI18N
        q6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q6ActionPerformed(evt);
            }
        });
        getContentPane().add(q6);
        q6.setBounds(190, 310, 50, 28);

        q7.setBackground(new java.awt.Color(255, 204, 204));
        q7.setFont(new java.awt.Font("High Tower Text", 3, 18)); // NOI18N
        getContentPane().add(q7);
        q7.setBounds(190, 340, 50, 28);

        q8.setBackground(new java.awt.Color(255, 204, 204));
        q8.setFont(new java.awt.Font("High Tower Text", 3, 18)); // NOI18N
        getContentPane().add(q8);
        q8.setBounds(190, 370, 50, 28);

        q9.setBackground(new java.awt.Color(255, 204, 204));
        q9.setFont(new java.awt.Font("High Tower Text", 3, 18)); // NOI18N
        getContentPane().add(q9);
        q9.setBounds(190, 400, 50, 28);

        q10.setBackground(new java.awt.Color(255, 204, 204));
        q10.setFont(new java.awt.Font("High Tower Text", 3, 18)); // NOI18N
        getContentPane().add(q10);
        q10.setBounds(190, 430, 50, 28);

        q15.setBackground(new java.awt.Color(255, 204, 204));
        q15.setFont(new java.awt.Font("High Tower Text", 3, 18)); // NOI18N
        getContentPane().add(q15);
        q15.setBounds(190, 630, 50, 28);

        q14.setBackground(new java.awt.Color(255, 204, 204));
        q14.setFont(new java.awt.Font("High Tower Text", 3, 18)); // NOI18N
        getContentPane().add(q14);
        q14.setBounds(190, 600, 50, 28);

        q13.setBackground(new java.awt.Color(255, 204, 204));
        q13.setFont(new java.awt.Font("High Tower Text", 3, 18)); // NOI18N
        getContentPane().add(q13);
        q13.setBounds(190, 570, 50, 28);

        q12.setBackground(new java.awt.Color(255, 204, 204));
        q12.setFont(new java.awt.Font("High Tower Text", 3, 18)); // NOI18N
        getContentPane().add(q12);
        q12.setBounds(190, 540, 50, 28);

        q11.setBackground(new java.awt.Color(255, 204, 204));
        q11.setFont(new java.awt.Font("High Tower Text", 3, 18)); // NOI18N
        getContentPane().add(q11);
        q11.setBounds(190, 510, 50, 28);

        jLabel23.setFont(new java.awt.Font("Gungsuh", 3, 14)); // NOI18N
        jLabel23.setText("DATE");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(520, 90, 150, 30);

        date.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });
        getContentPane().add(date);
        date.setBounds(720, 90, 37, 20);

        month.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "9", "10", "11", "12" }));
        month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthActionPerformed(evt);
            }
        });
        getContentPane().add(month);
        month.setBounds(790, 90, 37, 20);

        jLabel24.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel24.setText("-");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(770, 90, 20, 20);

        jLabel25.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel25.setText("-");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(840, 90, 20, 20);

        year.setEditable(true);
        year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2017", "2018", "2019", "2020" }));
        getContentPane().add(year);
        year.setBounds(860, 90, 100, 20);

        jLabel26.setFont(new java.awt.Font("Gungsuh", 3, 14)); // NOI18N
        jLabel26.setText("ORDER NUMBER");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(520, 140, 125, 20);

        on.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        on.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                onFocusGained(evt);
            }
        });
        on.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onMouseClicked(evt);
            }
        });
        on.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                onKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                onKeyTyped(evt);
            }
        });
        getContentPane().add(on);
        on.setBounds(720, 130, 240, 30);

        jLabel27.setFont(new java.awt.Font("Gungsuh", 3, 14)); // NOI18N
        jLabel27.setText("NAME OF CUSTOMER");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(520, 180, 161, 30);

        noc.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        noc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nocActionPerformed(evt);
            }
        });
        noc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nocKeyTyped(evt);
            }
        });
        getContentPane().add(noc);
        noc.setBounds(720, 180, 240, 30);

        jLabel28.setFont(new java.awt.Font("Gungsuh", 3, 14)); // NOI18N
        jLabel28.setText("PHONE NUMBER");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(520, 230, 124, 30);

        phn.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        phn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phnActionPerformed(evt);
            }
        });
        phn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phnKeyTyped(evt);
            }
        });
        getContentPane().add(phn);
        phn.setBounds(720, 230, 240, 30);

        jLabel29.setFont(new java.awt.Font("Gungsuh", 3, 14)); // NOI18N
        jLabel29.setText("NO. OF PEOPLE");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(520, 290, 140, 30);

        nop.setBackground(new java.awt.Color(204, 255, 255));
        nop.setEditable(true);
        nop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        nop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nopActionPerformed(evt);
            }
        });
        getContentPane().add(nop);
        nop.setBounds(720, 290, 240, 30);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MODE  OF  PAYMENT", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kristen ITC", 2, 14), new java.awt.Color(51, 51, 255))); // NOI18N
        jPanel5.setOpaque(false);

        buttonGroup1.add(ca);
        ca.setFont(new java.awt.Font("Century", 3, 14)); // NOI18N
        ca.setText("CASH");
        ca.setOpaque(false);

        buttonGroup1.add(cc);
        cc.setFont(new java.awt.Font("Century", 3, 14)); // NOI18N
        cc.setText("CREDIT CARD");
        cc.setOpaque(false);

        buttonGroup1.add(dc);
        dc.setFont(new java.awt.Font("Century", 3, 14)); // NOI18N
        dc.setText("DEBIT CARD");
        dc.setOpaque(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cc, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dc, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ca, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(ca, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cc, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dc, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(510, 380, 220, 150);

        jButton2.setFont(new java.awt.Font("Bookman Old Style", 3, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 51));
        jButton2.setText("PLACE");
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(780, 20, 120, 31);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon.png"))); // NOI18N
        jButton6.setToolTipText("<html><font color=\"RED\" face=\"JOKERMAN\">HOME</font></html>");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(930, 20, 50, 50);

        jButton69.setBackground(new java.awt.Color(204, 255, 204));
        jButton69.setText("Remove");
        jButton69.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton69ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton69);
        jButton69.setBounds(360, 640, 80, 23);

        jButton85.setBackground(new java.awt.Color(204, 255, 204));
        jButton85.setText("Remove");
        jButton85.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton85ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton85);
        jButton85.setBounds(360, 610, 80, 23);

        jButton86.setBackground(new java.awt.Color(204, 255, 204));
        jButton86.setText("Remove");
        jButton86.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton86ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton86);
        jButton86.setBounds(360, 100, 80, 23);

        jButton87.setBackground(new java.awt.Color(204, 255, 204));
        jButton87.setText("Remove");
        jButton87.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton87ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton87);
        jButton87.setBounds(360, 130, 80, 23);

        jButton88.setBackground(new java.awt.Color(204, 255, 204));
        jButton88.setText("Remove");
        jButton88.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton88ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton88);
        jButton88.setBounds(360, 160, 80, 23);

        jButton89.setBackground(new java.awt.Color(204, 255, 204));
        jButton89.setText("Remove");
        jButton89.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton89ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton89);
        jButton89.setBounds(360, 190, 80, 23);

        jButton90.setBackground(new java.awt.Color(204, 255, 204));
        jButton90.setText("Remove");
        jButton90.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton90ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton90);
        jButton90.setBounds(360, 220, 80, 23);

        jButton91.setBackground(new java.awt.Color(204, 255, 204));
        jButton91.setText("Remove");
        jButton91.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton91ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton91);
        jButton91.setBounds(360, 310, 80, 23);

        jButton92.setBackground(new java.awt.Color(204, 255, 204));
        jButton92.setText("Remove");
        jButton92.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton92ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton92);
        jButton92.setBounds(360, 340, 80, 23);

        jButton93.setBackground(new java.awt.Color(204, 255, 204));
        jButton93.setText("Remove");
        jButton93.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton93ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton93);
        jButton93.setBounds(360, 370, 80, 23);

        jButton94.setBackground(new java.awt.Color(204, 255, 204));
        jButton94.setText("Remove");
        jButton94.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton94ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton94);
        jButton94.setBounds(360, 400, 80, 23);

        jButton95.setBackground(new java.awt.Color(204, 255, 204));
        jButton95.setText("Remove");
        jButton95.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton95ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton95);
        jButton95.setBounds(360, 430, 80, 23);

        jButton96.setBackground(new java.awt.Color(204, 255, 204));
        jButton96.setText("Remove");
        jButton96.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton96ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton96);
        jButton96.setBounds(360, 520, 80, 23);

        jButton97.setBackground(new java.awt.Color(204, 255, 204));
        jButton97.setText("Remove");
        jButton97.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton97ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton97);
        jButton97.setBounds(360, 550, 80, 23);

        jButton98.setBackground(new java.awt.Color(204, 255, 204));
        jButton98.setText("Remove");
        jButton98.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton98ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton98);
        jButton98.setBounds(360, 580, 80, 23);

        jLabel30.setBackground(new java.awt.Color(255, 204, 204));
        jLabel30.setFont(new java.awt.Font("Chiller", 3, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 255));
        jLabel30.setText("ADD TO");
        getContentPane().add(jLabel30);
        jLabel30.setBounds(280, 10, 50, 22);

        jButton1.setFont(new java.awt.Font("Bookman Old Style", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 51));
        jButton1.setText("REFRESH");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(630, 20, 140, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgroundimagesection_c2a.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 1030, 700);

        setSize(new java.awt.Dimension(1052, 759));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
int f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12,f13,f14,f15;
int t1,t2,t3,t4,t5,t6,t7,t8,t9,t10,t11,t12,t13,t14,t15;
    private void jButton70ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton70ActionPerformed
        // TODO add your handling code here:
        try{
            rs = stmt.executeQuery("select * from menu where itemcode= 1;");
            f1=Integer.parseInt(q1.getText());
            while(rs.next()){
                icode = rs.getInt("itemcode");
                p = rs.getInt("price");
                fdname = rs.getString("itemname");
                t = rs.getString("type");
                t1=f1*p;
            }
            rs.close();
            stmt.close();
            con.close();
        } catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill values("+icode+", '"+ t +"' , '"+ fdname+"','"+ t1 + "')");
        JOptionPane.showMessageDialog(null,"Added Succesfully");
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_jButton70ActionPerformed

    private void jButton71ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton71ActionPerformed
        // TODO add your handling code here:
       try{
            rs = stmt.executeQuery("select * from menu where itemcode= 2;");
             f2=Integer.parseInt(q2.getText());
             while(rs.next()){
                icode = rs.getInt("itemcode");
                p = rs.getInt("price");
                fdname = rs.getString("itemname");
                t = rs.getString("type");
                t2=f2*p;
            }
            rs.close();
            stmt.close();
            con.close();
        } catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill values("+icode+", '"+ t +"' , '"+ fdname+"','"+ t2 + "')");
        JOptionPane.showMessageDialog(null,"Added Succesfully");
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_jButton71ActionPerformed

    private void jButton72ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton72ActionPerformed
        // TODO add your handling code here:
       try{
            rs = stmt.executeQuery("select * from menu where itemcode= 3;");
             f3=Integer.parseInt(q3.getText());
            while(rs.next()){
                icode = rs.getInt("itemcode");
                p = rs.getInt("price");
                fdname = rs.getString("itemname");
                t = rs.getString("type");
                t3=f3*p;
            }
            rs.close();
            stmt.close();
            con.close();
        } catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill values("+icode+", '"+ t +"' , '"+ fdname+"','"+ t3 + "')");
        JOptionPane.showMessageDialog(null,"Added Succesfully");
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_jButton72ActionPerformed

    private void jButton73ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton73ActionPerformed
        // TODO add your handling code here:
        try{
            rs = stmt.executeQuery("select * from menu where itemcode= 4;");
             f4=Integer.parseInt(q4.getText());
            while(rs.next()){
                icode = rs.getInt("itemcode");
                p = rs.getInt("price");
                fdname = rs.getString("itemname");
                t = rs.getString("type");
                t4=f4*p;
            }
            rs.close();
            stmt.close();
            con.close();
        } catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill values("+icode+", '"+ t +"' , '"+ fdname+"','"+ t4 + "')");
        JOptionPane.showMessageDialog(null,"Added Succesfully");
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_jButton73ActionPerformed

    private void jButton74ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton74ActionPerformed
        // TODO add your handling code here:
       try{
            rs = stmt.executeQuery("select * from menu where itemcode= 5;");
             f5=Integer.parseInt(q5.getText());
            while(rs.next()){
                icode = rs.getInt("itemcode");
                p = rs.getInt("price");
                fdname = rs.getString("itemname");
                t = rs.getString("type");
                t5=f5*p;
            }
            rs.close();
            stmt.close();
            con.close();
        } catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill values("+icode+", '"+ t +"' , '"+ fdname+"','"+ t5 + "')");
        JOptionPane.showMessageDialog(null,"Added Succesfully");
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_jButton74ActionPerformed

    private void jButton75ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton75ActionPerformed
        // TODO add your handling code here:
       try{
            rs = stmt.executeQuery("select * from menu where itemcode= 6;");
             f6=Integer.parseInt(q6.getText());
            while(rs.next()){
                icode = rs.getInt("itemcode");
                p = rs.getInt("price");
                fdname = rs.getString("itemname");
                t = rs.getString("type");
                t6=f6*p;
            }
            rs.close();
            stmt.close();
            con.close();
        } catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill values("+icode+", '"+ t +"' , '"+ fdname+"','"+ t6 + "')");
        JOptionPane.showMessageDialog(null,"Added Succesfully");
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_jButton75ActionPerformed

    private void jButton76ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton76ActionPerformed
        // TODO add your handling code here:
       try{
            rs = stmt.executeQuery("select * from menu where itemcode= 7;");
             f7=Integer.parseInt(q7.getText());
            while(rs.next()){
                icode = rs.getInt("itemcode");
                p = rs.getInt("price");
                fdname = rs.getString("itemname");
                t = rs.getString("type");
                t7=f7*p;
            }
            rs.close();
            stmt.close();
            con.close();
        } catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill values("+icode+", '"+ t +"' , '"+ fdname+"','"+ t7 + "')");
        JOptionPane.showMessageDialog(null,"Added Succesfully");
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_jButton76ActionPerformed

    private void jButton77ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton77ActionPerformed
        // TODO add your handling code here:
       try{
            rs = stmt.executeQuery("select * from menu where itemcode= 8;");
             f8=Integer.parseInt(q8.getText());
            while(rs.next()){
                icode = rs.getInt("itemcode");
                p = rs.getInt("price");
                fdname = rs.getString("itemname");
                t = rs.getString("type");
                t8=f8*p;
            }
            rs.close();
            stmt.close();
            con.close();
        } catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill values("+icode+", '"+ t +"' , '"+ fdname+"','"+ t8 + "')");
        JOptionPane.showMessageDialog(null,"Added Succesfully");
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_jButton77ActionPerformed

    private void jButton78ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton78ActionPerformed
        // TODO add your handling code here:
       try{
            rs = stmt.executeQuery("select * from menu where itemcode= 9;");

             f9=Integer.parseInt(q9.getText());
            while(rs.next()){
                icode = rs.getInt("itemcode");
                p = rs.getInt("price");
                fdname = rs.getString("itemname");
                t = rs.getString("type");
                t9=f9*p;
            }
            rs.close();
            stmt.close();
            con.close();
        } catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill values("+icode+", '"+ t +"' , '"+ fdname+"','"+ t9 + "')");
        JOptionPane.showMessageDialog(null,"Added Succesfully");
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_jButton78ActionPerformed

    private void jButton79ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton79ActionPerformed
        // TODO add your handling code here:
       try{
            rs = stmt.executeQuery("select * from menu where itemcode= 10;");
             f10=Integer.parseInt(q10.getText());
            while(rs.next()){
                icode = rs.getInt("itemcode");
                p = rs.getInt("price");
                fdname = rs.getString("itemname");
                t = rs.getString("type");
                t10=f10*p;
            }
            rs.close();
            stmt.close();
            con.close();
        } catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill values("+icode+", '"+ t +"' , '"+ fdname+"','"+ t10 + "')");
        JOptionPane.showMessageDialog(null,"Added Succesfully");
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_jButton79ActionPerformed

    private void jButton80ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton80ActionPerformed
        // TODO add your handling code here:
      try{
            rs = stmt.executeQuery("select * from menu where itemcode= 11;");
             f11=Integer.parseInt(q11.getText());
            while(rs.next()){
                icode = rs.getInt("itemcode");
                p = rs.getInt("price");
                fdname = rs.getString("itemname");
                t = rs.getString("type");
                t11=f11*p;
            }
            rs.close();
            stmt.close();
            con.close();
        } catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill values("+icode+", '"+ t +"' , '"+ fdname+"','"+ t11 + "')");
        JOptionPane.showMessageDialog(null,"Added Succesfully");
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_jButton80ActionPerformed

    private void jButton81ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton81ActionPerformed
        // TODO add your handling code here:
       try{
            rs = stmt.executeQuery("select * from menu where itemcode= 12;");
             f12=Integer.parseInt(q12.getText());
            while(rs.next()){
                icode = rs.getInt("itemcode");
                p = rs.getInt("price");
                fdname = rs.getString("itemname");
                t = rs.getString("type");
                t12=f12*p;
            }
            rs.close();
            stmt.close();
            con.close();
        } catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill values("+icode+", '"+ t +"' , '"+ fdname+"','"+ t12 + "')");
        JOptionPane.showMessageDialog(null,"Added Succesfully");
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_jButton81ActionPerformed

    private void jButton82ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton82ActionPerformed
        // TODO add your handling code here:
       try{
            rs = stmt.executeQuery("select * from menu where itemcode= 13;");
             f13=Integer.parseInt(q13.getText());
            while(rs.next()){
                icode = rs.getInt("itemcode");
                p = rs.getInt("price");
                fdname = rs.getString("itemname");
                t = rs.getString("type");
                t13=f13*p;
            }
            rs.close();
            stmt.close();
            con.close();
        } catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill values("+icode+", '"+ t +"' , '"+ fdname+"','"+ t13 + "')");
        JOptionPane.showMessageDialog(null,"Added Succesfully");
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_jButton82ActionPerformed

    private void jButton83ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton83ActionPerformed
        // TODO add your handling code here:
       try{
            rs = stmt.executeQuery("select * from menu where itemcode= 14;");
             f14=Integer.parseInt(q14.getText());
            while(rs.next()){
                icode = rs.getInt("itemcode");
                p = rs.getInt("price");
                fdname = rs.getString("itemname");
                t = rs.getString("type");
                t14=f14*p;
            }
            rs.close();
            stmt.close();
            con.close();
        } catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill values("+icode+", '"+ t +"' , '"+ fdname+"','"+ t14 + "')");
        JOptionPane.showMessageDialog(null,"Added Succesfully");
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_jButton83ActionPerformed

    private void jButton84ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton84ActionPerformed
        // TODO add your handling code here:
       try{
            rs = stmt.executeQuery("select * from menu where itemcode= 15;");
             f15=Integer.parseInt(q15.getText());
            while(rs.next()){
                icode = rs.getInt("itemcode");
                p = rs.getInt("price");
                fdname = rs.getString("itemname");
                t = rs.getString("type");
                t15=f15*p;
            }
            rs.close();
            stmt.close();
            con.close();
        } catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }

        try{Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
        stmt= con.createStatement();
        int a = stmt.executeUpdate("insert into bill values("+icode+", '"+ t +"' , '"+ fdname+"','"+ t15 + "')");
        JOptionPane.showMessageDialog(null,"Added Succesfully");
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_jButton84ActionPerformed

    private void q3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_q3ActionPerformed

    private void q6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q6ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_q6ActionPerformed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_dateActionPerformed

    private void monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_monthActionPerformed

    private void nocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nocActionPerformed

    private void phnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phnActionPerformed

    private void nopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nopActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_nopActionPerformed
String mp;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(phn.getText().length()>10||phn.getText().length()<10){
            JOptionPane.showMessageDialog(null,"ENTER VAID PHONE NUMBER X(");
        } else{
        try{
            Class.forName("java.sql.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","");
            String orno=on.getText();                       //Order number
            String d = (String) date.getSelectedItem();
            String m = (String) month.getSelectedItem();
            String y = (String) year.getSelectedItem();
            String dt=y+"-"+m+"-"+d;                        //Date
            String nc=noc.getText();                        //Name Of Customer
           String pn=phn.getText();                         //Phone Number
            String np= (String) nop.getSelectedItem();      //No. Of People
            if(ca.isSelected()==true){
                mp = "Cash";
            } else
                if(cc.isSelected()==true){                  //mode of payment
                    mp = "Credit Crard";
                } else
                    if(dc.isSelected()==true){
                        mp = "Debit Card";
                    }
            String query= "insert into orders values("+orno + ", '"+ dt + "' , '" + nc + "' , '"+ pn
                    +"' , '"+ np +"' , '"+ mp +" ' "+");";

            stmt=con.createStatement();
            int res=stmt.executeUpdate(query);

            JOptionPane.showMessageDialog(null,"!!!  THANK YOU FOR PLACING ORDER  !!!"+"\n \n (:  CLICK OK TO CONTINUE  :) ");
            Billing_Form bf = new Billing_Form();
            bf.setVisible(true);
            this.setVisible(false);
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Welcome_Screen_ ws=new Welcome_Screen_();
        ws.setVisible(true);
        this.setVisible(false);
}//GEN-LAST:event_jButton6ActionPerformed

    private void q1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q1ActionPerformed

    private void jButton69ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton69ActionPerformed
        // TODO add your handling code here:
      try{Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
            stmt= con.createStatement();
            int a = stmt.executeUpdate("Delete from bill where sno = 15;");
            rs.close();
            stmt.close();
            con.close();
            JOptionPane.showMessageDialog(null,"Removed Succesfully");
        }

        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
}//GEN-LAST:event_jButton69ActionPerformed

    private void jButton85ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton85ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
            stmt= con.createStatement();
            int a = stmt.executeUpdate("Delete from bill where sno = 14;");
            rs.close();
            stmt.close();
            con.close();
            JOptionPane.showMessageDialog(null,"Removed Succesfully");
        }

        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton85ActionPerformed

    private void jButton86ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton86ActionPerformed
        // TODO add your handling code here:
         try{Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
            stmt= con.createStatement();
            int a = stmt.executeUpdate("Delete from bill where sno = 1;");
            rs.close();
            stmt.close();
            con.close();
            JOptionPane.showMessageDialog(null,"Removed Succesfully");
        }

        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton86ActionPerformed

    private void jButton87ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton87ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
            stmt= con.createStatement();
            int a = stmt.executeUpdate("Delete from bill where sno = 2;");
            rs.close();
            stmt.close();
            con.close();
            JOptionPane.showMessageDialog(null,"Removed Succesfully");
        }

        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton87ActionPerformed

    private void jButton88ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton88ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
            stmt= con.createStatement();
            int a = stmt.executeUpdate("Delete from bill where sno = 3;");
            rs.close();
            stmt.close();
            con.close();
            JOptionPane.showMessageDialog(null,"Removed Succesfully");
        }

        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton88ActionPerformed

    private void jButton89ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton89ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
            stmt= con.createStatement();
            int a = stmt.executeUpdate("Delete from bill where sno = 4;");
            rs.close();
            stmt.close();
            con.close();
            JOptionPane.showMessageDialog(null,"Removed Succesfully");
        }

        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton89ActionPerformed

    private void jButton90ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton90ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
            stmt= con.createStatement();
            int a = stmt.executeUpdate("Delete from bill where sno = 5;");
            rs.close();
            stmt.close();
            con.close();
            JOptionPane.showMessageDialog(null,"Removed Succesfully");
        }

        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton90ActionPerformed

    private void jButton91ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton91ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
            stmt= con.createStatement();
            int a = stmt.executeUpdate("Delete from bill where sno = 6;");
            rs.close();
            stmt.close();
            con.close();
            JOptionPane.showMessageDialog(null,"Removed Succesfully");
        }

        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton91ActionPerformed

    private void jButton92ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton92ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
            stmt= con.createStatement();
            int a = stmt.executeUpdate("Delete from bill where sno = 7;");
            rs.close();
            stmt.close();
            con.close();
            JOptionPane.showMessageDialog(null,"Removed Succesfully");
        }

        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton92ActionPerformed

    private void jButton93ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton93ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
            stmt= con.createStatement();
            int a = stmt.executeUpdate("Delete from bill where sno = 8;");
            rs.close();
            stmt.close();
            con.close();
            JOptionPane.showMessageDialog(null,"Removed Succesfully");
        }

        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton93ActionPerformed

    private void jButton94ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton94ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
            stmt= con.createStatement();
            int a = stmt.executeUpdate("Delete from bill where sno = 9;");
            rs.close();
            stmt.close();
            con.close();
            JOptionPane.showMessageDialog(null,"Removed Succesfully");
        }

        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton94ActionPerformed

    private void jButton95ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton95ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
            stmt= con.createStatement();
            int a = stmt.executeUpdate("Delete from bill where sno = 10;");
            rs.close();
            stmt.close();
            con.close();
            JOptionPane.showMessageDialog(null,"Removed Succesfully");
        }

        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton95ActionPerformed

    private void jButton96ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton96ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
            stmt= con.createStatement();
            int a = stmt.executeUpdate("Delete from bill where sno = 11;");
            rs.close();
            stmt.close();
            con.close();
            JOptionPane.showMessageDialog(null,"Removed Succesfully");
        }

        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton96ActionPerformed

    private void jButton97ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton97ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
            stmt= con.createStatement();
            int a = stmt.executeUpdate("Delete from bill where sno = 12;");
            rs.close();
            stmt.close();
            con.close();
            JOptionPane.showMessageDialog(null,"Removed Succesfully");
        }

        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton97ActionPerformed

    private void jButton98ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton98ActionPerformed
        // TODO add your handling code here:
        try{Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
            stmt= con.createStatement();
            int a = stmt.executeUpdate("Delete from bill where sno = 13;");
            rs.close();
            stmt.close();
            con.close();
            JOptionPane.showMessageDialog(null,"Removed Succesfully");
        }

        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton98ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        q1.setText("");
        q2.setText("");
        q3.setText("");
        q4.setText("");
        q5.setText("");
        q6.setText("");
        q7.setText("");
        q8.setText("");
        q9.setText("");
        q10.setText("");
        q11.setText("");
        q12.setText("");
        q13.setText("");
        q14.setText("");
        q15.setText("");
        on.setText("");
        noc.setText("");
        phn.setText("");
        ca.setSelected(false);
        cc.setSelected(false);
        dc.setSelected(false);
        date.setSelectedIndex(0);
        month.setSelectedIndex(0);
        year.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void onMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onMouseClicked
        // TODO add your handling code here:   
        
    }//GEN-LAST:event_onMouseClicked

    private void onFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_onFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_onFocusGained

    private void onKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_onKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_onKeyPressed

    private void onKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_onKeyTyped
        // TODO add your handling code here:
        if(on.getText().equals("")){
            on.setBackground(Color.WHITE);
        }else
        {
           on.setBackground(Color.YELLOW); 
        }
    }//GEN-LAST:event_onKeyTyped

    private void nocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nocKeyTyped
        // TODO add your handling code here:
        if(noc.getText().equals("")){
            noc.setBackground(Color.WHITE);
        }else
        {
           noc.setBackground(Color.YELLOW); 
        }
    }//GEN-LAST:event_nocKeyTyped

    private void phnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phnKeyTyped
        // TODO add your handling code here:
        if(phn.getText().equals("")){
            phn.setBackground(Color.WHITE);
        }else
        {
           phn.setBackground(Color.YELLOW); 
        }
    }//GEN-LAST:event_phnKeyTyped

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Placing_Order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton ca;
    private javax.swing.JRadioButton cc;
    private javax.swing.JComboBox date;
    private javax.swing.JRadioButton dc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton70;
    private javax.swing.JButton jButton71;
    private javax.swing.JButton jButton72;
    private javax.swing.JButton jButton73;
    private javax.swing.JButton jButton74;
    private javax.swing.JButton jButton75;
    private javax.swing.JButton jButton76;
    private javax.swing.JButton jButton77;
    private javax.swing.JButton jButton78;
    private javax.swing.JButton jButton79;
    private javax.swing.JButton jButton80;
    private javax.swing.JButton jButton81;
    private javax.swing.JButton jButton82;
    private javax.swing.JButton jButton83;
    private javax.swing.JButton jButton84;
    private javax.swing.JButton jButton85;
    private javax.swing.JButton jButton86;
    private javax.swing.JButton jButton87;
    private javax.swing.JButton jButton88;
    private javax.swing.JButton jButton89;
    private javax.swing.JButton jButton90;
    private javax.swing.JButton jButton91;
    private javax.swing.JButton jButton92;
    private javax.swing.JButton jButton93;
    private javax.swing.JButton jButton94;
    private javax.swing.JButton jButton95;
    private javax.swing.JButton jButton96;
    private javax.swing.JButton jButton97;
    private javax.swing.JButton jButton98;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JComboBox month;
    private javax.swing.JTextField noc;
    private javax.swing.JComboBox nop;
    private javax.swing.JTextField on;
    private javax.swing.JTextField phn;
    private javax.swing.JTextField q1;
    private javax.swing.JTextField q10;
    private javax.swing.JTextField q11;
    private javax.swing.JTextField q12;
    private javax.swing.JTextField q13;
    private javax.swing.JTextField q14;
    private javax.swing.JTextField q15;
    private javax.swing.JTextField q2;
    private javax.swing.JTextField q3;
    private javax.swing.JTextField q4;
    private javax.swing.JTextField q5;
    private javax.swing.JTextField q6;
    private javax.swing.JTextField q7;
    private javax.swing.JTextField q8;
    private javax.swing.JTextField q9;
    private javax.swing.JComboBox year;
    // End of variables declaration//GEN-END:variables

}
