import java.sql.*;
import javax.swing.JOptionPane;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Sign_up.java
 *
 * Created on Oct 10, 2017, 7:08:57 PM
 */
/**
 *
 * @author Yuvansh
 */
public class Sign_up extends javax.swing.JFrame {
    Connection con= null;
Statement stmt = null;
ResultSet rs= null;
int n = 0;

    /** Creates new form Sign_up */
    public Sign_up() {
        initComponents();
   //      try{
   //          Class.forName("com.mysql.jdbc.Driver");
   //     con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","");
  //    stmt = con.createStatement();
  //     rs = stmt.executeQuery("select * from signup;");
  //    while (rs.last()){
  //    n = rs.getInt("sno");
  //    }
  //     rs.close();
 //      stmt.close();
 //      con.close();
 //    }
//
 //      catch(Exception e)
 //     {
 //          JOptionPane.showMessageDialog(null,e);
//  }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        ps = new javax.swing.JCheckBox();
        tc = new javax.swing.JCheckBox();
        CreateAccount = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        phnu = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(834, 554));
        getContentPane().setLayout(null);

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(255, 255, 204));
        jTextArea2.setColumns(5);
        jTextArea2.setForeground(new java.awt.Color(51, 51, 51));
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setTabSize(6);
        jTextArea2.setText("You are to accept the terms and conditions of this program so as to be an user of it. This program solely belongs to MILI , YUVANSH , GARGI and YOGESH only who have the authorised right to change the program. You are only authorised to go through the content and enjoy its facilities. The contents displayed in this program are taken from some other sites and we don't sell foods in reality.\n\n   !!! \n\n          HOPE YOU WILL ENJOY OUR SERVICES \n                    \n                                                                                                     !!!");
        jTextArea2.setWrapStyleWord(true);
        jScrollPane3.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(450, 140, 350, 280);

        jLabel6.setBackground(new java.awt.Color(204, 204, 255));
        jLabel6.setForeground(new java.awt.Color(255, 255, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/471074.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(610, 20, 200, 90);

        jLabel7.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel7.setText("* First Name:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 170, 140, 30);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(210, 170, 170, 20);

        jLabel8.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel8.setText("Last Name:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 210, 120, 20);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(210, 210, 170, 20);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(210, 320, 170, 20);

        jLabel10.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel10.setText("* Password:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 320, 140, 20);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(210, 280, 170, 20);

        jLabel11.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel11.setText("*Username:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 280, 120, 20);

        jLabel13.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel13.setText("* Confirm Passsword:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(30, 360, 170, 20);
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(210, 360, 170, 20);

        ps.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        ps.setText("Show Password");
        ps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psActionPerformed(evt);
            }
        });
        getContentPane().add(ps);
        ps.setBounds(30, 400, 149, 20);

        tc.setForeground(new java.awt.Color(51, 51, 51));
        tc.setText("I agree to all the terms and ");
        tc.setContentAreaFilled(false);
        tc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcActionPerformed(evt);
            }
        });
        getContentPane().add(tc);
        tc.setBounds(30, 430, 210, 30);

        CreateAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thumbnail.png"))); // NOI18N
        CreateAccount.setEnabled(false);
        CreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateAccountActionPerformed(evt);
            }
        });
        getContentPane().add(CreateAccount);
        CreateAccount.setBounds(230, 430, 150, 40);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 102));
        jLabel12.setText("*compulsory fields");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(270, 400, 120, 20);

        jLabel3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel3.setText("*Phone Number");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 240, 130, 30);

        phnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phnuActionPerformed(evt);
            }
        });
        getContentPane().add(phnu);
        phnu.setBounds(210, 250, 170, 20);

        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Condition");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 460, 100, 20);

        jTextArea1.setBackground(new java.awt.Color(153, 255, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SIGN UP", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 102, 153))); // NOI18N
        jTextArea1.setOpaque(false);
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 130, 400, 370);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon.png"))); // NOI18N
        jButton8.setToolTipText("<html><font color=\"RED\" face=\"JOKERMAN\">HOME</font></html>");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(20, 20, 50, 50);

        jLabel1.setFont(new java.awt.Font("Castellar", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SIGN UP WIZARD");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 30, 520, 40);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testimonials-background-desktop-new.jpg"))); // NOI18N
        jLabel14.setPreferredSize(new java.awt.Dimension(800, 500));
        getContentPane().add(jLabel14);
        jLabel14.setBounds(0, 0, 820, 530);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon.png"))); // NOI18N
        jButton6.setToolTipText("<html><font color=\"RED\" face=\"JOKERMAN\">HOME</font></html>");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(1270, 20, 50, 50);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon.png"))); // NOI18N
        jButton7.setToolTipText("<html><font color=\"RED\" face=\"JOKERMAN\">HOME</font></html>");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(1270, 20, 50, 50);

        setSize(new java.awt.Dimension(837, 572));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextField1ActionPerformed

    private void CreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAccountActionPerformed
        // TODO add your handling code here:
        try{
            n= n+1;
               Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","");
       stmt = con.createStatement();
       rs = stmt.executeQuery("select * from signup;");
            String f_name = jTextField1.getText();
            String l_name = jTextField2.getText();
            String pnu = phnu.getText();
            String uname = jTextField3.getText();
            String pass = new String(jPasswordField1.getPassword());
            String cpass = new String(jPasswordField2.getPassword());      
            if (f_name.length()== 0) {
               JOptionPane.showMessageDialog(null,"First name field is empty!");
            }

               if (uname.length()== 0){
                   JOptionPane.showMessageDialog(null,"Give the valid UserName.");
                }
                else {
                    if(pass.equals(cpass)){
                        try{
                            Class.forName("com.mysql.jdbc.Driver");
                            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","");
                            stmt = con.createStatement();
                            String query= "insert into signup values("+ n + ", '"+ f_name + "' , '" + l_name + "' , '"+ uname
                                                                                    +"' , '"+ pass +"' , '"+ cpass+"' , '"+pnu+ "' );";
                            int m = stmt.executeUpdate(query);

                            String show = "You Have Successfully Signed Up With GARNISH. We Hope That You'll Enjoy Our Service." +
                                          "\n Your Username is :" + uname + " \n Your Password is :"+ pass;
                             while (rs.next()){
       n = rs.getInt("sno");

                              
       }JOptionPane.showMessageDialog(null,show);
                               Login_Form lf2 =new Login_Form();
                               lf2.setVisible(true);
                               this.setVisible(false);
                         
                        } catch(Exception e) {
                           JOptionPane.showMessageDialog(null,e);
                       }
                    }else
                    {
                        JOptionPane.showMessageDialog(null,"Fill password correctly.");
                     }
       }
            rs.close();
       stmt.close();
       con.close();
        }
                        catch(Exception e) {
                            JOptionPane.showMessageDialog(null,e);
                       }
                    


    }//GEN-LAST:event_CreateAccountActionPerformed

    private void tcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcActionPerformed
        // TODO add your handling code here:
        if(tc.isSelected()==true){
        CreateAccount.setEnabled(true);
        } else
            if(tc.isSelected()==false){
        CreateAccount.setEnabled(false);
        }
}//GEN-LAST:event_tcActionPerformed

    private void psActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psActionPerformed
        // TODO add your handling code here:
        if(ps.isSelected()==true){
            jPasswordField1.setEchoChar((char)0);
            jPasswordField2.setEchoChar((char)0);
        } else {
            jPasswordField1.setEchoChar('\u25cf');
            jPasswordField2.setEchoChar('\u25cf');
        }
    }//GEN-LAST:event_psActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Welcome_Screen_ ws=new Welcome_Screen_();
        ws.setVisible(true);
        this.setVisible(false);
}//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        Welcome_Screen_ ws=new Welcome_Screen_();
        ws.setVisible(true);
        this.setVisible(false);
}//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        Login_Form lf=new Login_Form();
        lf.setVisible(true);
        this.setVisible(false);
}//GEN-LAST:event_jButton8ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void phnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phnuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phnuActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sign_up().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateAccount;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField phnu;
    private javax.swing.JCheckBox ps;
    private javax.swing.JCheckBox tc;
    // End of variables declaration//GEN-END:variables

}
