import java.sql.*;
import javax.swing.JOptionPane;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Testimonials.java
 *
 * Created on Nov 16, 2017, 9:36:11 PM
 */

/**
 *
 * @author Yuvansh
 */
public class Testimonials extends javax.swing.JFrame {
Connection con = null;
Statement stmt = null;
ResultSet rs= null;
    /** Creates new form Testimonials */
    public Testimonials() {
        initComponents();
          try{
              Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
        stmt= con.createStatement();
        rs = stmt.executeQuery("Select *  from feedback;");
        int i=1;
      while(rs.next()){
        String n = rs.getString("Name");
         String p = rs.getString("Phone_Number");
          String s = rs.getString("Service");
           String q = rs.getString("Quality");
            String c = rs.getString("Cleanliness");
             String r = rs.getString("Response");
              String re = rs.getString("Review");
               String ra = rs.getString("Rating");

        cmt.append(" "+i++ +"."+" "+n +"\n"+"\n"+" "+"RATING :"+" "+ra+"\n"+"\n"+" "+"SERVICE :"+"\t"+s+"\n"+"\n"+" "+"QUALITY :"+" "+
                q+"\n"+"\n"+" "+"CLEANLINESS :"+" "+c+"\n"+"\n"+" "+"RESPONSE TIME :"+" "+r+"\n"+"\n"+" "+"REVIEW :"+" "+re+"\n"+"\n"+
                "~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*"+"\n");
        cmt.setCaretPosition(0);
        }
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cmt = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(818, 538));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon.png"))); // NOI18N
        jButton6.setToolTipText("<html><font color=\"RED\" face=\"JOKERMAN\">HOME</font></html>");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(730, 20, 50, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testimonial_logo_clear (4).png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 10, 430, 100);

        cmt.setBackground(new java.awt.Color(132, 252, 243));
        cmt.setColumns(20);
        cmt.setEditable(false);
        cmt.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        cmt.setForeground(new java.awt.Color(204, 0, 0));
        cmt.setLineWrap(true);
        cmt.setRows(5);
        cmt.setWrapStyleWord(true);
        cmt.setAutoscrolls(false);
        cmt.setBorder(null);
        cmt.setCaretColor(new java.awt.Color(255, 204, 51));
        cmt.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jScrollPane1.setViewportView(cmt);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(90, 210, 420, 280);

        jLabel5.setBackground(new java.awt.Color(204, 204, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/471074.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(530, 20, 200, 92);

        jLabel7.setFont(new java.awt.Font("Forte", 2, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 204));
        jLabel7.setText("~THE OCEAN OF TASTES");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(560, 110, 210, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thanks.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(610, 170, 180, 160);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(500, 320, 300, 170);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smile.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 80, 350, 120);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 500);

        setSize(new java.awt.Dimension(817, 542));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowStateChanged

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentHidden

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Welcome_Screen_ ws=new Welcome_Screen_();
        ws.setVisible(true);
        this.setVisible(false);
}//GEN-LAST:event_jButton6ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Testimonials().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea cmt;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
