import java.awt.Font;
import java.sql.*;
import javax.swing.JOptionPane;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Welcome_Screen1.java
 *
 * Created on Aug 5, 2017, 8:16:45 PM
 */

/**
 *
 * @author Yuvansh
 */
public class Welcome_Screen_ extends javax.swing.JFrame {
    Connection con = null;
        Statement stmt= null;
        ResultSet rs =null;

    /** Creates new form Welcome_Screen1 */
    public Welcome_Screen_() {
        initComponents();
      try{
            Class.forName("com.mysql.jdbc.Driver");
          con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","");
        stmt= con.createStatement();
         ResultSet ros = stmt.executeQuery("select fname, lname from username u ,signup s where u.uname=s.username;");
         Font font =new Font("CHILLER",Font.BOLD,26);
          while(ros.next()){
        String f = ros.getString("fname");
        String l = ros.getString("lname");
        String cm=f+" "+l;
        unm.setFont(font);
        unm.setText(""+cm);
        }
         }
        catch(Exception e)
                 {
            JOptionPane.showMessageDialog(null,e);
        }
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        unm = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(895, 520));
        getContentPane().setLayout(null);

        jLabel3.setBackground(new java.awt.Color(204, 204, 255));
        jLabel3.setForeground(new java.awt.Color(255, 255, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 0, 0);

        jLabel1.setBackground(new java.awt.Color(255, 153, 153));
        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WELCOME ,");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 20, 140, 30);

        jButton2.setBackground(new java.awt.Color(255, 204, 204));
        jButton2.setForeground(new java.awt.Color(102, 102, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/547202582.jpg"))); // NOI18N
        jButton2.setToolTipText("<html><font color=\"RED\" face=\"JOKERMAN\">LOGOUT</font></html>");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(250, 50, 70, 50);

        jLabel4.setBackground(new java.awt.Color(204, 204, 255));
        jLabel4.setForeground(new java.awt.Color(255, 255, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 0, 0);

        jLabel5.setBackground(new java.awt.Color(204, 204, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/471074.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 10, 200, 92);

        jButton15.setBackground(new java.awt.Color(255, 255, 153));
        jButton15.setForeground(new java.awt.Color(255, 0, 51));
        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testimonial_icon.png"))); // NOI18N
        jButton15.setToolTipText("<html><font color=\"RED\" face=\"JOKERMAN\">ABOUT US</font></html>");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15);
        jButton15.setBounds(750, 10, 50, 50);

        jButton14.setBackground(new java.awt.Color(255, 255, 153));
        jButton14.setForeground(new java.awt.Color(255, 0, 51));
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/240_F_62102461_yHUiioo3lvh3pKRdh2gyAxz9AU2IHhu6.jpg"))); // NOI18N
        jButton14.setToolTipText("<html><font color=\"RED\" face=\"JOKERMAN\">CONTACT US</font></html>");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14);
        jButton14.setBounds(810, 10, 60, 50);

        jButton9.setBackground(new java.awt.Color(255, 255, 153));
        jButton9.setForeground(new java.awt.Color(255, 0, 51));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1036_-_Cancel_Order-512.png"))); // NOI18N
        jButton9.setToolTipText("<html><font color=\"RED\" face=\"JOKERMAN\">CANCEL ORDER</font></html>");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(250, 260, 100, 90);

        jButton7.setBackground(new java.awt.Color(255, 255, 153));
        jButton7.setForeground(new java.awt.Color(255, 0, 51));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/26575-200.png"))); // NOI18N
        jButton7.setToolTipText("<html><font color=\"RED\" face=\"JOKERMAN\">HIOME DELIVERY</font></html>");
        jButton7.setBorderPainted(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(250, 160, 100, 90);

        jButton10.setBackground(new java.awt.Color(255, 255, 153));
        jButton10.setForeground(new java.awt.Color(255, 0, 51));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafe-menu-cover.jpg"))); // NOI18N
        jButton10.setToolTipText("<html><font color=\"RED\" face=\"JOKERMAN\">MENU</font></html>");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(100, 320, 100, 130);

        jButton13.setBackground(new java.awt.Color(255, 255, 153));
        jButton13.setForeground(new java.awt.Color(255, 0, 51));
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot (28).jpg"))); // NOI18N
        jButton13.setToolTipText("<html><font color=\"RED\" face=\"JOKERMAN\">INFO UPDATE</font></html>");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13);
        jButton13.setBounds(250, 360, 100, 90);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/table-img.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(390, 130, 370, 320);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurants-icon.jpg"))); // NOI18N
        jButton3.setToolTipText("<html><font color=\"RED\" face=\"JOKERMAN\">PLACE ORDER</font></html>");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(100, 160, 100, 140);

        unm.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        unm.setForeground(new java.awt.Color(102, 204, 255));
        getContentPane().add(unm);
        unm.setBounds(380, 20, 220, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/review.jpg"))); // NOI18N
        jButton1.setToolTipText("<html><font color=\"RED\" face=\"JOKERMAN\">TESTIMONIALS</font></html>");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(790, 70, 80, 70);

        jLabel7.setFont(new java.awt.Font("Forte", 2, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 255, 255));
        jLabel7.setText("~THE OCEAN OF TASTES");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 100, 210, 20);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/6919347-abstract-nice-3d-artwork.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 880, 480);

        setSize(new java.awt.Dimension(895, 518));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         try{
              Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
        stmt= con.createStatement();
        int  rps = stmt.executeUpdate("delete from username;");
        }
         catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
        Login_Form lf=new Login_Form();
        lf.setVisible(true);
        this.setVisible(false);
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        Contact_Us cu=new Contact_Us();
        cu.setVisible(true);
        this.setVisible(false);
}//GEN-LAST:event_jButton14ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        Cancel_Order oh=new Cancel_Order();
        oh.setVisible(true);
        this.setVisible(false);
}//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        Home_Delivery hd=new Home_Delivery();
        hd.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        Menu_Card mc=new Menu_Card();
        mc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        About_Us au=new About_Us();
        au.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        Info_Update iu=new Info_Update();
        iu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Placing_Order po=new Placing_Order();
        po.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Testimonials ts= new Testimonials();
        ts.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome_Screen_().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel unm;
    // End of variables declaration//GEN-END:variables

}
